// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/img_syncer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListByDateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY:MM:DD
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	MaxReturn     int32                  `protobuf:"varint,3,opt,name=maxReturn,proto3" json:"maxReturn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByDateRequest) Reset() {
	*x = ListByDateRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByDateRequest) ProtoMessage() {}

func (x *ListByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByDateRequest.ProtoReflect.Descriptor instead.
func (*ListByDateRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{0}
}

func (x *ListByDateRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ListByDateRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListByDateRequest) GetMaxReturn() int32 {
	if x != nil {
		return x.MaxReturn
	}
	return 0
}

type ListByDateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Paths         []string               `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByDateResponse) Reset() {
	*x = ListByDateResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByDateResponse) ProtoMessage() {}

func (x *ListByDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByDateResponse.ProtoReflect.Descriptor instead.
func (*ListByDateResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{1}
}

func (x *ListByDateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListByDateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListByDateResponse) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FilterNotUploadedRequestInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterNotUploadedRequestInfo) Reset() {
	*x = FilterNotUploadedRequestInfo{}
	mi := &file_proto_img_syncer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterNotUploadedRequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterNotUploadedRequestInfo) ProtoMessage() {}

func (x *FilterNotUploadedRequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterNotUploadedRequestInfo.ProtoReflect.Descriptor instead.
func (*FilterNotUploadedRequestInfo) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{4}
}

func (x *FilterNotUploadedRequestInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilterNotUploadedRequestInfo) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *FilterNotUploadedRequestInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FilterNotUploadedRequest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Photos        []*FilterNotUploadedRequestInfo `protobuf:"bytes,1,rep,name=photos,proto3" json:"photos,omitempty"`
	IsFinished    bool                            `protobuf:"varint,2,opt,name=isFinished,proto3" json:"isFinished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterNotUploadedRequest) Reset() {
	*x = FilterNotUploadedRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterNotUploadedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterNotUploadedRequest) ProtoMessage() {}

func (x *FilterNotUploadedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterNotUploadedRequest.ProtoReflect.Descriptor instead.
func (*FilterNotUploadedRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{5}
}

func (x *FilterNotUploadedRequest) GetPhotos() []*FilterNotUploadedRequestInfo {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *FilterNotUploadedRequest) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

type FilterNotUploadedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NotUploaedIDs []string               `protobuf:"bytes,3,rep,name=notUploaedIDs,proto3" json:"notUploaedIDs,omitempty"`
	IsFinished    bool                   `protobuf:"varint,4,opt,name=isFinished,proto3" json:"isFinished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterNotUploadedResponse) Reset() {
	*x = FilterNotUploadedResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterNotUploadedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterNotUploadedResponse) ProtoMessage() {}

func (x *FilterNotUploadedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterNotUploadedResponse.ProtoReflect.Descriptor instead.
func (*FilterNotUploadedResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{6}
}

func (x *FilterNotUploadedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FilterNotUploadedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FilterNotUploadedResponse) GetNotUploaedIDs() []string {
	if x != nil {
		return x.NotUploaedIDs
	}
	return nil
}

func (x *FilterNotUploadedResponse) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

type SetDriveSMBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Share         string                 `protobuf:"bytes,4,opt,name=share,proto3" json:"share,omitempty"`
	Root          string                 `protobuf:"bytes,5,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveSMBRequest) Reset() {
	*x = SetDriveSMBRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveSMBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveSMBRequest) ProtoMessage() {}

func (x *SetDriveSMBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveSMBRequest.ProtoReflect.Descriptor instead.
func (*SetDriveSMBRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{7}
}

func (x *SetDriveSMBRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *SetDriveSMBRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetDriveSMBRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SetDriveSMBRequest) GetShare() string {
	if x != nil {
		return x.Share
	}
	return ""
}

func (x *SetDriveSMBRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type SetDriveSMBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveSMBResponse) Reset() {
	*x = SetDriveSMBResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveSMBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveSMBResponse) ProtoMessage() {}

func (x *SetDriveSMBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveSMBResponse.ProtoReflect.Descriptor instead.
func (*SetDriveSMBResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{8}
}

func (x *SetDriveSMBResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetDriveSMBResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListDriveSMBSharesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveSMBSharesRequest) Reset() {
	*x = ListDriveSMBSharesRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveSMBSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveSMBSharesRequest) ProtoMessage() {}

func (x *ListDriveSMBSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveSMBSharesRequest.ProtoReflect.Descriptor instead.
func (*ListDriveSMBSharesRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{9}
}

type ListDriveSMBSharesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Shares        []string               `protobuf:"bytes,3,rep,name=shares,proto3" json:"shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveSMBSharesResponse) Reset() {
	*x = ListDriveSMBSharesResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveSMBSharesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveSMBSharesResponse) ProtoMessage() {}

func (x *ListDriveSMBSharesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveSMBSharesResponse.ProtoReflect.Descriptor instead.
func (*ListDriveSMBSharesResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{10}
}

func (x *ListDriveSMBSharesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListDriveSMBSharesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListDriveSMBSharesResponse) GetShares() []string {
	if x != nil {
		return x.Shares
	}
	return nil
}

type ListDriveSMBDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         string                 `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	Dir           string                 `protobuf:"bytes,2,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveSMBDirRequest) Reset() {
	*x = ListDriveSMBDirRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveSMBDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveSMBDirRequest) ProtoMessage() {}

func (x *ListDriveSMBDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveSMBDirRequest.ProtoReflect.Descriptor instead.
func (*ListDriveSMBDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{11}
}

func (x *ListDriveSMBDirRequest) GetShare() string {
	if x != nil {
		return x.Share
	}
	return ""
}

func (x *ListDriveSMBDirRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type ListDriveSMBDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Dirs          []string               `protobuf:"bytes,3,rep,name=dirs,proto3" json:"dirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveSMBDirResponse) Reset() {
	*x = ListDriveSMBDirResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveSMBDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveSMBDirResponse) ProtoMessage() {}

func (x *ListDriveSMBDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveSMBDirResponse.ProtoReflect.Descriptor instead.
func (*ListDriveSMBDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{12}
}

func (x *ListDriveSMBDirResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListDriveSMBDirResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListDriveSMBDirResponse) GetDirs() []string {
	if x != nil {
		return x.Dirs
	}
	return nil
}

type SetDriveSMBShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         string                 `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	Root          string                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveSMBShareRequest) Reset() {
	*x = SetDriveSMBShareRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveSMBShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveSMBShareRequest) ProtoMessage() {}

func (x *SetDriveSMBShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveSMBShareRequest.ProtoReflect.Descriptor instead.
func (*SetDriveSMBShareRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{13}
}

func (x *SetDriveSMBShareRequest) GetShare() string {
	if x != nil {
		return x.Share
	}
	return ""
}

func (x *SetDriveSMBShareRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type SetDriveSMBShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveSMBShareResponse) Reset() {
	*x = SetDriveSMBShareResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveSMBShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveSMBShareResponse) ProtoMessage() {}

func (x *SetDriveSMBShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveSMBShareResponse.ProtoReflect.Descriptor instead.
func (*SetDriveSMBShareResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{14}
}

func (x *SetDriveSMBShareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetDriveSMBShareResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SetDriveWebdavRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Root          string                 `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveWebdavRequest) Reset() {
	*x = SetDriveWebdavRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveWebdavRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveWebdavRequest) ProtoMessage() {}

func (x *SetDriveWebdavRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveWebdavRequest.ProtoReflect.Descriptor instead.
func (*SetDriveWebdavRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{15}
}

func (x *SetDriveWebdavRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *SetDriveWebdavRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetDriveWebdavRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SetDriveWebdavRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type SetDriveWebdavResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveWebdavResponse) Reset() {
	*x = SetDriveWebdavResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveWebdavResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveWebdavResponse) ProtoMessage() {}

func (x *SetDriveWebdavResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveWebdavResponse.ProtoReflect.Descriptor instead.
func (*SetDriveWebdavResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{16}
}

func (x *SetDriveWebdavResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetDriveWebdavResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListDriveWebdavDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveWebdavDirRequest) Reset() {
	*x = ListDriveWebdavDirRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveWebdavDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveWebdavDirRequest) ProtoMessage() {}

func (x *ListDriveWebdavDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveWebdavDirRequest.ProtoReflect.Descriptor instead.
func (*ListDriveWebdavDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{17}
}

func (x *ListDriveWebdavDirRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type ListDriveWebdavDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Dirs          []string               `protobuf:"bytes,3,rep,name=dirs,proto3" json:"dirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveWebdavDirResponse) Reset() {
	*x = ListDriveWebdavDirResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveWebdavDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveWebdavDirResponse) ProtoMessage() {}

func (x *ListDriveWebdavDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveWebdavDirResponse.ProtoReflect.Descriptor instead.
func (*ListDriveWebdavDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{18}
}

func (x *ListDriveWebdavDirResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListDriveWebdavDirResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListDriveWebdavDirResponse) GetDirs() []string {
	if x != nil {
		return x.Dirs
	}
	return nil
}

type SetDriveNFSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Root          string                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveNFSRequest) Reset() {
	*x = SetDriveNFSRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveNFSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveNFSRequest) ProtoMessage() {}

func (x *SetDriveNFSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveNFSRequest.ProtoReflect.Descriptor instead.
func (*SetDriveNFSRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{19}
}

func (x *SetDriveNFSRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *SetDriveNFSRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type SetDriveNFSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveNFSResponse) Reset() {
	*x = SetDriveNFSResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveNFSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveNFSResponse) ProtoMessage() {}

func (x *SetDriveNFSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveNFSResponse.ProtoReflect.Descriptor instead.
func (*SetDriveNFSResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{20}
}

func (x *SetDriveNFSResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetDriveNFSResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListDriveNFSDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveNFSDirRequest) Reset() {
	*x = ListDriveNFSDirRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveNFSDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveNFSDirRequest) ProtoMessage() {}

func (x *ListDriveNFSDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveNFSDirRequest.ProtoReflect.Descriptor instead.
func (*ListDriveNFSDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{21}
}

func (x *ListDriveNFSDirRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type ListDriveNFSDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Dirs          []string               `protobuf:"bytes,3,rep,name=dirs,proto3" json:"dirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveNFSDirResponse) Reset() {
	*x = ListDriveNFSDirResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveNFSDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveNFSDirResponse) ProtoMessage() {}

func (x *ListDriveNFSDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveNFSDirResponse.ProtoReflect.Descriptor instead.
func (*ListDriveNFSDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{22}
}

func (x *ListDriveNFSDirResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListDriveNFSDirResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListDriveNFSDirResponse) GetDirs() []string {
	if x != nil {
		return x.Dirs
	}
	return nil
}

type SetDriveBaiduNetDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	TmpDir        string                 `protobuf:"bytes,3,opt,name=tmpDir,proto3" json:"tmpDir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveBaiduNetDiskRequest) Reset() {
	*x = SetDriveBaiduNetDiskRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveBaiduNetDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveBaiduNetDiskRequest) ProtoMessage() {}

func (x *SetDriveBaiduNetDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveBaiduNetDiskRequest.ProtoReflect.Descriptor instead.
func (*SetDriveBaiduNetDiskRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{23}
}

func (x *SetDriveBaiduNetDiskRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SetDriveBaiduNetDiskRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SetDriveBaiduNetDiskRequest) GetTmpDir() string {
	if x != nil {
		return x.TmpDir
	}
	return ""
}

type SetDriveBaiduNetDiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveBaiduNetDiskResponse) Reset() {
	*x = SetDriveBaiduNetDiskResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveBaiduNetDiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveBaiduNetDiskResponse) ProtoMessage() {}

func (x *SetDriveBaiduNetDiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveBaiduNetDiskResponse.ProtoReflect.Descriptor instead.
func (*SetDriveBaiduNetDiskResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{24}
}

func (x *SetDriveBaiduNetDiskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetDriveBaiduNetDiskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartBaiduNetdiskLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmpDir        string                 `protobuf:"bytes,1,opt,name=tmpDir,proto3" json:"tmpDir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBaiduNetdiskLoginRequest) Reset() {
	*x = StartBaiduNetdiskLoginRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBaiduNetdiskLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBaiduNetdiskLoginRequest) ProtoMessage() {}

func (x *StartBaiduNetdiskLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBaiduNetdiskLoginRequest.ProtoReflect.Descriptor instead.
func (*StartBaiduNetdiskLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{25}
}

func (x *StartBaiduNetdiskLoginRequest) GetTmpDir() string {
	if x != nil {
		return x.TmpDir
	}
	return ""
}

type StartBaiduNetdiskLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	AccessToken   string                 `protobuf:"bytes,4,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	ExiresAt      int64                  `protobuf:"varint,5,opt,name=exiresAt,proto3" json:"exiresAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBaiduNetdiskLoginResponse) Reset() {
	*x = StartBaiduNetdiskLoginResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBaiduNetdiskLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBaiduNetdiskLoginResponse) ProtoMessage() {}

func (x *StartBaiduNetdiskLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBaiduNetdiskLoginResponse.ProtoReflect.Descriptor instead.
func (*StartBaiduNetdiskLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{26}
}

func (x *StartBaiduNetdiskLoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartBaiduNetdiskLoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartBaiduNetdiskLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *StartBaiduNetdiskLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *StartBaiduNetdiskLoginResponse) GetExiresAt() int64 {
	if x != nil {
		return x.ExiresAt
	}
	return 0
}

type MoveToTrashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToTrashRequest) Reset() {
	*x = MoveToTrashRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToTrashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToTrashRequest) ProtoMessage() {}

func (x *MoveToTrashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToTrashRequest.ProtoReflect.Descriptor instead.
func (*MoveToTrashRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{27}
}

func (x *MoveToTrashRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type MoveToTrashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToTrashResponse) Reset() {
	*x = MoveToTrashResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToTrashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToTrashResponse) ProtoMessage() {}

func (x *MoveToTrashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToTrashResponse.ProtoReflect.Descriptor instead.
func (*MoveToTrashResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{28}
}

func (x *MoveToTrashResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MoveToTrashResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TrashItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalPath  string                 `protobuf:"bytes,1,opt,name=originalPath,proto3" json:"originalPath,omitempty"`
	TrashPath     string                 `protobuf:"bytes,2,opt,name=trashPath,proto3" json:"trashPath,omitempty"`
	TrashedAt     int64                  `protobuf:"varint,3,opt,name=trashedAt,proto3" json:"trashedAt,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrashItem) Reset() {
	*x = TrashItem{}
	mi := &file_proto_img_syncer_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrashItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrashItem) ProtoMessage() {}

func (x *TrashItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrashItem.ProtoReflect.Descriptor instead.
func (*TrashItem) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{29}
}

func (x *TrashItem) GetOriginalPath() string {
	if x != nil {
		return x.OriginalPath
	}
	return ""
}

func (x *TrashItem) GetTrashPath() string {
	if x != nil {
		return x.TrashPath
	}
	return ""
}

func (x *TrashItem) GetTrashedAt() int64 {
	if x != nil {
		return x.TrashedAt
	}
	return 0
}

func (x *TrashItem) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListTrashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	MaxReturn     int32                  `protobuf:"varint,2,opt,name=maxReturn,proto3" json:"maxReturn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrashRequest) Reset() {
	*x = ListTrashRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrashRequest) ProtoMessage() {}

func (x *ListTrashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrashRequest.ProtoReflect.Descriptor instead.
func (*ListTrashRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{30}
}

func (x *ListTrashRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTrashRequest) GetMaxReturn() int32 {
	if x != nil {
		return x.MaxReturn
	}
	return 0
}

type ListTrashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Items         []*TrashItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrashResponse) Reset() {
	*x = ListTrashResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrashResponse) ProtoMessage() {}

func (x *ListTrashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrashResponse.ProtoReflect.Descriptor instead.
func (*ListTrashResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{31}
}

func (x *ListTrashResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListTrashResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListTrashResponse) GetItems() []*TrashItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RestoreFromTrashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrashPaths    []string               `protobuf:"bytes,1,rep,name=trashPaths,proto3" json:"trashPaths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFromTrashRequest) Reset() {
	*x = RestoreFromTrashRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromTrashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromTrashRequest) ProtoMessage() {}

func (x *RestoreFromTrashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFromTrashRequest.ProtoReflect.Descriptor instead.
func (*RestoreFromTrashRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{32}
}

func (x *RestoreFromTrashRequest) GetTrashPaths() []string {
	if x != nil {
		return x.TrashPaths
	}
	return nil
}

type RestoreFromTrashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFromTrashResponse) Reset() {
	*x = RestoreFromTrashResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromTrashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromTrashResponse) ProtoMessage() {}

func (x *RestoreFromTrashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFromTrashResponse.ProtoReflect.Descriptor instead.
func (*RestoreFromTrashResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{33}
}

func (x *RestoreFromTrashResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreFromTrashResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EmptyTrashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyTrashRequest) Reset() {
	*x = EmptyTrashRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyTrashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyTrashRequest) ProtoMessage() {}

func (x *EmptyTrashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyTrashRequest.ProtoReflect.Descriptor instead.
func (*EmptyTrashRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{34}
}

type EmptyTrashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyTrashResponse) Reset() {
	*x = EmptyTrashResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyTrashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyTrashResponse) ProtoMessage() {}

func (x *EmptyTrashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyTrashResponse.ProtoReflect.Descriptor instead.
func (*EmptyTrashResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{35}
}

func (x *EmptyTrashResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmptyTrashResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_img_syncer_proto protoreflect.FileDescriptor

const file_proto_img_syncer_proto_rawDesc = "" +
	"\n" +
	"\x16proto/img_syncer.proto\x12\n" +
	"img_syncer\"]\n" +
	"\x11ListByDateRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1c\n" +
	"\tmaxReturn\x18\x03 \x01(\x05R\tmaxReturn\"^\n" +
	"\x12ListByDateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05paths\x18\x03 \x03(\tR\x05paths\"%\n" +
	"\rDeleteRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\x1cFilterNotUploadedRequestInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"|\n" +
	"\x18FilterNotUploadedRequest\x12@\n" +
	"\x06photos\x18\x01 \x03(\v2(.img_syncer.FilterNotUploadedRequestInfoR\x06photos\x12\x1e\n" +
	"\n" +
	"isFinished\x18\x02 \x01(\bR\n" +
	"isFinished\"\x95\x01\n" +
	"\x19FilterNotUploadedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\rnotUploaedIDs\x18\x03 \x03(\tR\rnotUploaedIDs\x12\x1e\n" +
	"\n" +
	"isFinished\x18\x04 \x01(\bR\n" +
	"isFinished\"\x8a\x01\n" +
	"\x12SetDriveSMBRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05share\x18\x04 \x01(\tR\x05share\x12\x12\n" +
	"\x04root\x18\x05 \x01(\tR\x04root\"I\n" +
	"\x13SetDriveSMBResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1b\n" +
	"\x19ListDriveSMBSharesRequest\"h\n" +
	"\x1aListDriveSMBSharesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06shares\x18\x03 \x03(\tR\x06shares\"@\n" +
	"\x16ListDriveSMBDirRequest\x12\x14\n" +
	"\x05share\x18\x01 \x01(\tR\x05share\x12\x10\n" +
	"\x03dir\x18\x02 \x01(\tR\x03dir\"a\n" +
	"\x17ListDriveSMBDirResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04dirs\x18\x03 \x03(\tR\x04dirs\"C\n" +
	"\x17SetDriveSMBShareRequest\x12\x14\n" +
	"\x05share\x18\x01 \x01(\tR\x05share\x12\x12\n" +
	"\x04root\x18\x02 \x01(\tR\x04root\"N\n" +
	"\x18SetDriveSMBShareResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"w\n" +
	"\x15SetDriveWebdavRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04root\x18\x04 \x01(\tR\x04root\"L\n" +
	"\x16SetDriveWebdavResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x19ListDriveWebdavDirRequest\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\"d\n" +
	"\x1aListDriveWebdavDirResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04dirs\x18\x03 \x03(\tR\x04dirs\"<\n" +
	"\x12SetDriveNFSRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04root\x18\x02 \x01(\tR\x04root\"I\n" +
	"\x13SetDriveNFSResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\x16ListDriveNFSDirRequest\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\"a\n" +
	"\x17ListDriveNFSDirResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04dirs\x18\x03 \x03(\tR\x04dirs\"{\n" +
	"\x1bSetDriveBaiduNetDiskRequest\x12\"\n" +
	"\frefreshToken\x18\x01 \x01(\tR\frefreshToken\x12 \n" +
	"\vaccessToken\x18\x02 \x01(\tR\vaccessToken\x12\x16\n" +
	"\x06tmpDir\x18\x03 \x01(\tR\x06tmpDir\"R\n" +
	"\x1cSetDriveBaiduNetDiskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"7\n" +
	"\x1dStartBaiduNetdiskLoginRequest\x12\x16\n" +
	"\x06tmpDir\x18\x01 \x01(\tR\x06tmpDir\"\xb6\x01\n" +
	"\x1eStartBaiduNetdiskLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\frefreshToken\x18\x03 \x01(\tR\frefreshToken\x12 \n" +
	"\vaccessToken\x18\x04 \x01(\tR\vaccessToken\x12\x1a\n" +
	"\bexiresAt\x18\x05 \x01(\x03R\bexiresAt\"*\n" +
	"\x12MoveToTrashRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"I\n" +
	"\x13MoveToTrashResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x7f\n" +
	"\tTrashItem\x12\"\n" +
	"\foriginalPath\x18\x01 \x01(\tR\foriginalPath\x12\x1c\n" +
	"\ttrashPath\x18\x02 \x01(\tR\ttrashPath\x12\x1c\n" +
	"\ttrashedAt\x18\x03 \x01(\x03R\ttrashedAt\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"H\n" +
	"\x10ListTrashRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x1c\n" +
	"\tmaxReturn\x18\x02 \x01(\x05R\tmaxReturn\"t\n" +
	"\x11ListTrashResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x05items\x18\x03 \x03(\v2\x15.img_syncer.TrashItemR\x05items\"9\n" +
	"\x17RestoreFromTrashRequest\x12\x1e\n" +
	"\n" +
	"trashPaths\x18\x01 \x03(\tR\n" +
	"trashPaths\"N\n" +
	"\x18RestoreFromTrashResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11EmptyTrashRequest\"H\n" +
	"\x12EmptyTrashResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9d\f\n" +
	"\tImgSyncer\x12M\n" +
	"\n" +
	"ListByDate\x12\x1d.img_syncer.ListByDateRequest\x1a\x1e.img_syncer.ListByDateResponse\"\x00\x12A\n" +
	"\x06Delete\x12\x19.img_syncer.DeleteRequest\x1a\x1a.img_syncer.DeleteResponse\"\x00\x12f\n" +
	"\x11FilterNotUploaded\x12$.img_syncer.FilterNotUploadedRequest\x1a%.img_syncer.FilterNotUploadedResponse\"\x00(\x010\x01\x12P\n" +
	"\vSetDriveSMB\x12\x1e.img_syncer.SetDriveSMBRequest\x1a\x1f.img_syncer.SetDriveSMBResponse\"\x00\x12e\n" +
	"\x12ListDriveSMBShares\x12%.img_syncer.ListDriveSMBSharesRequest\x1a&.img_syncer.ListDriveSMBSharesResponse\"\x00\x12\\\n" +
	"\x0fListDriveSMBDir\x12\".img_syncer.ListDriveSMBDirRequest\x1a#.img_syncer.ListDriveSMBDirResponse\"\x00\x12_\n" +
	"\x10SetDriveSMBShare\x12#.img_syncer.SetDriveSMBShareRequest\x1a$.img_syncer.SetDriveSMBShareResponse\"\x00\x12Y\n" +
	"\x0eSetDriveWebdav\x12!.img_syncer.SetDriveWebdavRequest\x1a\".img_syncer.SetDriveWebdavResponse\"\x00\x12e\n" +
	"\x12ListDriveWebdavDir\x12%.img_syncer.ListDriveWebdavDirRequest\x1a&.img_syncer.ListDriveWebdavDirResponse\"\x00\x12P\n" +
	"\vSetDriveNFS\x12\x1e.img_syncer.SetDriveNFSRequest\x1a\x1f.img_syncer.SetDriveNFSResponse\"\x00\x12\\\n" +
	"\x0fListDriveNFSDir\x12\".img_syncer.ListDriveNFSDirRequest\x1a#.img_syncer.ListDriveNFSDirResponse\"\x00\x12k\n" +
	"\x14SetDriveBaiduNetDisk\x12'.img_syncer.SetDriveBaiduNetDiskRequest\x1a(.img_syncer.SetDriveBaiduNetDiskResponse\"\x00\x12q\n" +
	"\x16StartBaiduNetdiskLogin\x12).img_syncer.StartBaiduNetdiskLoginRequest\x1a*.img_syncer.StartBaiduNetdiskLoginResponse\"\x00\x12P\n" +
	"\vMoveToTrash\x12\x1e.img_syncer.MoveToTrashRequest\x1a\x1f.img_syncer.MoveToTrashResponse\"\x00\x12J\n" +
	"\tListTrash\x12\x1c.img_syncer.ListTrashRequest\x1a\x1d.img_syncer.ListTrashResponse\"\x00\x12_\n" +
	"\x10RestoreFromTrash\x12#.img_syncer.RestoreFromTrashRequest\x1a$.img_syncer.RestoreFromTrashResponse\"\x00\x12M\n" +
	"\n" +
	"EmptyTrash\x12\x1d.img_syncer.EmptyTrashRequest\x1a\x1e.img_syncer.EmptyTrashResponse\"\x00B$Z\"github.com/fregie/img_syncer/protob\x06proto3"

var (
	file_proto_img_syncer_proto_rawDescOnce sync.Once
	file_proto_img_syncer_proto_rawDescData []byte
)

func file_proto_img_syncer_proto_rawDescGZIP() []byte {
	file_proto_img_syncer_proto_rawDescOnce.Do(func() {
		file_proto_img_syncer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_img_syncer_proto_rawDesc), len(file_proto_img_syncer_proto_rawDesc)))
	})
	return file_proto_img_syncer_proto_rawDescData
}

var file_proto_img_syncer_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_proto_img_syncer_proto_goTypes = []any{
	(*ListByDateRequest)(nil),              // 0: img_syncer.ListByDateRequest
	(*ListByDateResponse)(nil),             // 1: img_syncer.ListByDateResponse
	(*DeleteRequest)(nil),                  // 2: img_syncer.DeleteRequest
	(*DeleteResponse)(nil),                 // 3: img_syncer.DeleteResponse
	(*FilterNotUploadedRequestInfo)(nil),   // 4: img_syncer.FilterNotUploadedRequestInfo
	(*FilterNotUploadedRequest)(nil),       // 5: img_syncer.FilterNotUploadedRequest
	(*FilterNotUploadedResponse)(nil),      // 6: img_syncer.FilterNotUploadedResponse
	(*SetDriveSMBRequest)(nil),             // 7: img_syncer.SetDriveSMBRequest
	(*SetDriveSMBResponse)(nil),            // 8: img_syncer.SetDriveSMBResponse
	(*ListDriveSMBSharesRequest)(nil),      // 9: img_syncer.ListDriveSMBSharesRequest
	(*ListDriveSMBSharesResponse)(nil),     // 10: img_syncer.ListDriveSMBSharesResponse
	(*ListDriveSMBDirRequest)(nil),         // 11: img_syncer.ListDriveSMBDirRequest
	(*ListDriveSMBDirResponse)(nil),        // 12: img_syncer.ListDriveSMBDirResponse
	(*SetDriveSMBShareRequest)(nil),        // 13: img_syncer.SetDriveSMBShareRequest
	(*SetDriveSMBShareResponse)(nil),       // 14: img_syncer.SetDriveSMBShareResponse
	(*SetDriveWebdavRequest)(nil),          // 15: img_syncer.SetDriveWebdavRequest
	(*SetDriveWebdavResponse)(nil),         // 16: img_syncer.SetDriveWebdavResponse
	(*ListDriveWebdavDirRequest)(nil),      // 17: img_syncer.ListDriveWebdavDirRequest
	(*ListDriveWebdavDirResponse)(nil),     // 18: img_syncer.ListDriveWebdavDirResponse
	(*SetDriveNFSRequest)(nil),             // 19: img_syncer.SetDriveNFSRequest
	(*SetDriveNFSResponse)(nil),            // 20: img_syncer.SetDriveNFSResponse
	(*ListDriveNFSDirRequest)(nil),         // 21: img_syncer.ListDriveNFSDirRequest
	(*ListDriveNFSDirResponse)(nil),        // 22: img_syncer.ListDriveNFSDirResponse
	(*SetDriveBaiduNetDiskRequest)(nil),    // 23: img_syncer.SetDriveBaiduNetDiskRequest
	(*SetDriveBaiduNetDiskResponse)(nil),   // 24: img_syncer.SetDriveBaiduNetDiskResponse
	(*StartBaiduNetdiskLoginRequest)(nil),  // 25: img_syncer.StartBaiduNetdiskLoginRequest
	(*StartBaiduNetdiskLoginResponse)(nil), // 26: img_syncer.StartBaiduNetdiskLoginResponse
	(*MoveToTrashRequest)(nil),             // 27: img_syncer.MoveToTrashRequest
	(*MoveToTrashResponse)(nil),            // 28: img_syncer.MoveToTrashResponse
	(*TrashItem)(nil),                      // 29: img_syncer.TrashItem
	(*ListTrashRequest)(nil),               // 30: img_syncer.ListTrashRequest
	(*ListTrashResponse)(nil),              // 31: img_syncer.ListTrashResponse
	(*RestoreFromTrashRequest)(nil),        // 32: img_syncer.RestoreFromTrashRequest
	(*RestoreFromTrashResponse)(nil),       // 33: img_syncer.RestoreFromTrashResponse
	(*EmptyTrashRequest)(nil),              // 34: img_syncer.EmptyTrashRequest
	(*EmptyTrashResponse)(nil),             // 35: img_syncer.EmptyTrashResponse
}
var file_proto_img_syncer_proto_depIdxs = []int32{
	4,  // 0: img_syncer.FilterNotUploadedRequest.photos:type_name -> img_syncer.FilterNotUploadedRequestInfo
	29, // 1: img_syncer.ListTrashResponse.items:type_name -> img_syncer.TrashItem
	0,  // 2: img_syncer.ImgSyncer.ListByDate:input_type -> img_syncer.ListByDateRequest
	2,  // 3: img_syncer.ImgSyncer.Delete:input_type -> img_syncer.DeleteRequest
	5,  // 4: img_syncer.ImgSyncer.FilterNotUploaded:input_type -> img_syncer.FilterNotUploadedRequest
	7,  // 5: img_syncer.ImgSyncer.SetDriveSMB:input_type -> img_syncer.SetDriveSMBRequest
	9,  // 6: img_syncer.ImgSyncer.ListDriveSMBShares:input_type -> img_syncer.ListDriveSMBSharesRequest
	11, // 7: img_syncer.ImgSyncer.ListDriveSMBDir:input_type -> img_syncer.ListDriveSMBDirRequest
	13, // 8: img_syncer.ImgSyncer.SetDriveSMBShare:input_type -> img_syncer.SetDriveSMBShareRequest
	15, // 9: img_syncer.ImgSyncer.SetDriveWebdav:input_type -> img_syncer.SetDriveWebdavRequest
	17, // 10: img_syncer.ImgSyncer.ListDriveWebdavDir:input_type -> img_syncer.ListDriveWebdavDirRequest
	19, // 11: img_syncer.ImgSyncer.SetDriveNFS:input_type -> img_syncer.SetDriveNFSRequest
	21, // 12: img_syncer.ImgSyncer.ListDriveNFSDir:input_type -> img_syncer.ListDriveNFSDirRequest
	23, // 13: img_syncer.ImgSyncer.SetDriveBaiduNetDisk:input_type -> img_syncer.SetDriveBaiduNetDiskRequest
	25, // 14: img_syncer.ImgSyncer.StartBaiduNetdiskLogin:input_type -> img_syncer.StartBaiduNetdiskLoginRequest
	27, // 15: img_syncer.ImgSyncer.MoveToTrash:input_type -> img_syncer.MoveToTrashRequest
	30, // 16: img_syncer.ImgSyncer.ListTrash:input_type -> img_syncer.ListTrashRequest
	32, // 17: img_syncer.ImgSyncer.RestoreFromTrash:input_type -> img_syncer.RestoreFromTrashRequest
	34, // 18: img_syncer.ImgSyncer.EmptyTrash:input_type -> img_syncer.EmptyTrashRequest
	1,  // 19: img_syncer.ImgSyncer.ListByDate:output_type -> img_syncer.ListByDateResponse
	3,  // 20: img_syncer.ImgSyncer.Delete:output_type -> img_syncer.DeleteResponse
	6,  // 21: img_syncer.ImgSyncer.FilterNotUploaded:output_type -> img_syncer.FilterNotUploadedResponse
	8,  // 22: img_syncer.ImgSyncer.SetDriveSMB:output_type -> img_syncer.SetDriveSMBResponse
	10, // 23: img_syncer.ImgSyncer.ListDriveSMBShares:output_type -> img_syncer.ListDriveSMBSharesResponse
	12, // 24: img_syncer.ImgSyncer.ListDriveSMBDir:output_type -> img_syncer.ListDriveSMBDirResponse
	14, // 25: img_syncer.ImgSyncer.SetDriveSMBShare:output_type -> img_syncer.SetDriveSMBShareResponse
	16, // 26: img_syncer.ImgSyncer.SetDriveWebdav:output_type -> img_syncer.SetDriveWebdavResponse
	18, // 27: img_syncer.ImgSyncer.ListDriveWebdavDir:output_type -> img_syncer.ListDriveWebdavDirResponse
	20, // 28: img_syncer.ImgSyncer.SetDriveNFS:output_type -> img_syncer.SetDriveNFSResponse
	22, // 29: img_syncer.ImgSyncer.ListDriveNFSDir:output_type -> img_syncer.ListDriveNFSDirResponse
	24, // 30: img_syncer.ImgSyncer.SetDriveBaiduNetDisk:output_type -> img_syncer.SetDriveBaiduNetDiskResponse
	26, // 31: img_syncer.ImgSyncer.StartBaiduNetdiskLogin:output_type -> img_syncer.StartBaiduNetdiskLoginResponse
	28, // 32: img_syncer.ImgSyncer.MoveToTrash:output_type -> img_syncer.MoveToTrashResponse
	31, // 33: img_syncer.ImgSyncer.ListTrash:output_type -> img_syncer.ListTrashResponse
	33, // 34: img_syncer.ImgSyncer.RestoreFromTrash:output_type -> img_syncer.RestoreFromTrashResponse
	35, // 35: img_syncer.ImgSyncer.EmptyTrash:output_type -> img_syncer.EmptyTrashResponse
	19, // [19:36] is the sub-list for method output_type
	2,  // [2:19] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_img_syncer_proto_init() }
func file_proto_img_syncer_proto_init() {
	if File_proto_img_syncer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_img_syncer_proto_rawDesc), len(file_proto_img_syncer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_img_syncer_proto_goTypes,
		DependencyIndexes: file_proto_img_syncer_proto_depIdxs,
		MessageInfos:      file_proto_img_syncer_proto_msgTypes,
	}.Build()
	File_proto_img_syncer_proto = out.File
	file_proto_img_syncer_proto_goTypes = nil
	file_proto_img_syncer_proto_depIdxs = nil
}
