// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/img_syncer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListByDateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY:MM:DD
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	MaxReturn     int32                  `protobuf:"varint,3,opt,name=maxReturn,proto3" json:"maxReturn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByDateRequest) Reset() {
	*x = ListByDateRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByDateRequest) ProtoMessage() {}

func (x *ListByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByDateRequest.ProtoReflect.Descriptor instead.
func (*ListByDateRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{0}
}

func (x *ListByDateRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ListByDateRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListByDateRequest) GetMaxReturn() int32 {
	if x != nil {
		return x.MaxReturn
	}
	return 0
}

type ListByDateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Paths         []string               `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByDateResponse) Reset() {
	*x = ListByDateResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByDateResponse) ProtoMessage() {}

func (x *ListByDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByDateResponse.ProtoReflect.Descriptor instead.
func (*ListByDateResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{1}
}

func (x *ListByDateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListByDateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListByDateResponse) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FilterNotUploadedRequestInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterNotUploadedRequestInfo) Reset() {
	*x = FilterNotUploadedRequestInfo{}
	mi := &file_proto_img_syncer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterNotUploadedRequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterNotUploadedRequestInfo) ProtoMessage() {}

func (x *FilterNotUploadedRequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterNotUploadedRequestInfo.ProtoReflect.Descriptor instead.
func (*FilterNotUploadedRequestInfo) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{4}
}

func (x *FilterNotUploadedRequestInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilterNotUploadedRequestInfo) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *FilterNotUploadedRequestInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FilterNotUploadedRequest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Photos        []*FilterNotUploadedRequestInfo `protobuf:"bytes,1,rep,name=photos,proto3" json:"photos,omitempty"`
	IsFinished    bool                            `protobuf:"varint,2,opt,name=isFinished,proto3" json:"isFinished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterNotUploadedRequest) Reset() {
	*x = FilterNotUploadedRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterNotUploadedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterNotUploadedRequest) ProtoMessage() {}

func (x *FilterNotUploadedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterNotUploadedRequest.ProtoReflect.Descriptor instead.
func (*FilterNotUploadedRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{5}
}

func (x *FilterNotUploadedRequest) GetPhotos() []*FilterNotUploadedRequestInfo {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *FilterNotUploadedRequest) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

type FilterNotUploadedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NotUploaedIDs []string               `protobuf:"bytes,3,rep,name=notUploaedIDs,proto3" json:"notUploaedIDs,omitempty"`
	IsFinished    bool                   `protobuf:"varint,4,opt,name=isFinished,proto3" json:"isFinished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterNotUploadedResponse) Reset() {
	*x = FilterNotUploadedResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterNotUploadedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterNotUploadedResponse) ProtoMessage() {}

func (x *FilterNotUploadedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterNotUploadedResponse.ProtoReflect.Descriptor instead.
func (*FilterNotUploadedResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{6}
}

func (x *FilterNotUploadedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FilterNotUploadedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FilterNotUploadedResponse) GetNotUploaedIDs() []string {
	if x != nil {
		return x.NotUploaedIDs
	}
	return nil
}

func (x *FilterNotUploadedResponse) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

type SetDriveSMBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Share         string                 `protobuf:"bytes,4,opt,name=share,proto3" json:"share,omitempty"`
	Root          string                 `protobuf:"bytes,5,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveSMBRequest) Reset() {
	*x = SetDriveSMBRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveSMBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveSMBRequest) ProtoMessage() {}

func (x *SetDriveSMBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveSMBRequest.ProtoReflect.Descriptor instead.
func (*SetDriveSMBRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{7}
}

func (x *SetDriveSMBRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *SetDriveSMBRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetDriveSMBRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SetDriveSMBRequest) GetShare() string {
	if x != nil {
		return x.Share
	}
	return ""
}

func (x *SetDriveSMBRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type SetDriveSMBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveSMBResponse) Reset() {
	*x = SetDriveSMBResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveSMBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveSMBResponse) ProtoMessage() {}

func (x *SetDriveSMBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveSMBResponse.ProtoReflect.Descriptor instead.
func (*SetDriveSMBResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{8}
}

func (x *SetDriveSMBResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetDriveSMBResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListDriveSMBSharesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveSMBSharesRequest) Reset() {
	*x = ListDriveSMBSharesRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveSMBSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveSMBSharesRequest) ProtoMessage() {}

func (x *ListDriveSMBSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveSMBSharesRequest.ProtoReflect.Descriptor instead.
func (*ListDriveSMBSharesRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{9}
}

type ListDriveSMBSharesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Shares        []string               `protobuf:"bytes,3,rep,name=shares,proto3" json:"shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveSMBSharesResponse) Reset() {
	*x = ListDriveSMBSharesResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveSMBSharesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveSMBSharesResponse) ProtoMessage() {}

func (x *ListDriveSMBSharesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveSMBSharesResponse.ProtoReflect.Descriptor instead.
func (*ListDriveSMBSharesResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{10}
}

func (x *ListDriveSMBSharesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListDriveSMBSharesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListDriveSMBSharesResponse) GetShares() []string {
	if x != nil {
		return x.Shares
	}
	return nil
}

type ListDriveSMBDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         string                 `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	Dir           string                 `protobuf:"bytes,2,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveSMBDirRequest) Reset() {
	*x = ListDriveSMBDirRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveSMBDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveSMBDirRequest) ProtoMessage() {}

func (x *ListDriveSMBDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveSMBDirRequest.ProtoReflect.Descriptor instead.
func (*ListDriveSMBDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{11}
}

func (x *ListDriveSMBDirRequest) GetShare() string {
	if x != nil {
		return x.Share
	}
	return ""
}

func (x *ListDriveSMBDirRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type ListDriveSMBDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Dirs          []string               `protobuf:"bytes,3,rep,name=dirs,proto3" json:"dirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveSMBDirResponse) Reset() {
	*x = ListDriveSMBDirResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveSMBDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveSMBDirResponse) ProtoMessage() {}

func (x *ListDriveSMBDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveSMBDirResponse.ProtoReflect.Descriptor instead.
func (*ListDriveSMBDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{12}
}

func (x *ListDriveSMBDirResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListDriveSMBDirResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListDriveSMBDirResponse) GetDirs() []string {
	if x != nil {
		return x.Dirs
	}
	return nil
}

type SetDriveSMBShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         string                 `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	Root          string                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveSMBShareRequest) Reset() {
	*x = SetDriveSMBShareRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveSMBShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveSMBShareRequest) ProtoMessage() {}

func (x *SetDriveSMBShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveSMBShareRequest.ProtoReflect.Descriptor instead.
func (*SetDriveSMBShareRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{13}
}

func (x *SetDriveSMBShareRequest) GetShare() string {
	if x != nil {
		return x.Share
	}
	return ""
}

func (x *SetDriveSMBShareRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type SetDriveSMBShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveSMBShareResponse) Reset() {
	*x = SetDriveSMBShareResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveSMBShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveSMBShareResponse) ProtoMessage() {}

func (x *SetDriveSMBShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveSMBShareResponse.ProtoReflect.Descriptor instead.
func (*SetDriveSMBShareResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{14}
}

func (x *SetDriveSMBShareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetDriveSMBShareResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SetDriveWebdavRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Root          string                 `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveWebdavRequest) Reset() {
	*x = SetDriveWebdavRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveWebdavRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveWebdavRequest) ProtoMessage() {}

func (x *SetDriveWebdavRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveWebdavRequest.ProtoReflect.Descriptor instead.
func (*SetDriveWebdavRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{15}
}

func (x *SetDriveWebdavRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *SetDriveWebdavRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetDriveWebdavRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SetDriveWebdavRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type SetDriveWebdavResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveWebdavResponse) Reset() {
	*x = SetDriveWebdavResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveWebdavResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveWebdavResponse) ProtoMessage() {}

func (x *SetDriveWebdavResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveWebdavResponse.ProtoReflect.Descriptor instead.
func (*SetDriveWebdavResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{16}
}

func (x *SetDriveWebdavResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetDriveWebdavResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListDriveWebdavDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveWebdavDirRequest) Reset() {
	*x = ListDriveWebdavDirRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveWebdavDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveWebdavDirRequest) ProtoMessage() {}

func (x *ListDriveWebdavDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveWebdavDirRequest.ProtoReflect.Descriptor instead.
func (*ListDriveWebdavDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{17}
}

func (x *ListDriveWebdavDirRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type ListDriveWebdavDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Dirs          []string               `protobuf:"bytes,3,rep,name=dirs,proto3" json:"dirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveWebdavDirResponse) Reset() {
	*x = ListDriveWebdavDirResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveWebdavDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveWebdavDirResponse) ProtoMessage() {}

func (x *ListDriveWebdavDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveWebdavDirResponse.ProtoReflect.Descriptor instead.
func (*ListDriveWebdavDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{18}
}

func (x *ListDriveWebdavDirResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListDriveWebdavDirResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListDriveWebdavDirResponse) GetDirs() []string {
	if x != nil {
		return x.Dirs
	}
	return nil
}

type SetDriveNFSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Root          string                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveNFSRequest) Reset() {
	*x = SetDriveNFSRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveNFSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveNFSRequest) ProtoMessage() {}

func (x *SetDriveNFSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveNFSRequest.ProtoReflect.Descriptor instead.
func (*SetDriveNFSRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{19}
}

func (x *SetDriveNFSRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *SetDriveNFSRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type SetDriveNFSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveNFSResponse) Reset() {
	*x = SetDriveNFSResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveNFSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveNFSResponse) ProtoMessage() {}

func (x *SetDriveNFSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveNFSResponse.ProtoReflect.Descriptor instead.
func (*SetDriveNFSResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{20}
}

func (x *SetDriveNFSResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetDriveNFSResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListDriveNFSDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveNFSDirRequest) Reset() {
	*x = ListDriveNFSDirRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveNFSDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveNFSDirRequest) ProtoMessage() {}

func (x *ListDriveNFSDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveNFSDirRequest.ProtoReflect.Descriptor instead.
func (*ListDriveNFSDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{21}
}

func (x *ListDriveNFSDirRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type ListDriveNFSDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Dirs          []string               `protobuf:"bytes,3,rep,name=dirs,proto3" json:"dirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveNFSDirResponse) Reset() {
	*x = ListDriveNFSDirResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveNFSDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveNFSDirResponse) ProtoMessage() {}

func (x *ListDriveNFSDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveNFSDirResponse.ProtoReflect.Descriptor instead.
func (*ListDriveNFSDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{22}
}

func (x *ListDriveNFSDirResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListDriveNFSDirResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListDriveNFSDirResponse) GetDirs() []string {
	if x != nil {
		return x.Dirs
	}
	return nil
}

type SetDriveS3Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Endpoint        string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Region          string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	AccessKeyId     string                 `protobuf:"bytes,3,opt,name=accessKeyId,proto3" json:"accessKeyId,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,4,opt,name=secretAccessKey,proto3" json:"secretAccessKey,omitempty"`
	Bucket          string                 `protobuf:"bytes,5,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Root            string                 `protobuf:"bytes,6,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetDriveS3Request) Reset() {
	*x = SetDriveS3Request{}
	mi := &file_proto_img_syncer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveS3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveS3Request) ProtoMessage() {}

func (x *SetDriveS3Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveS3Request.ProtoReflect.Descriptor instead.
func (*SetDriveS3Request) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{23}
}

func (x *SetDriveS3Request) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *SetDriveS3Request) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *SetDriveS3Request) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *SetDriveS3Request) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *SetDriveS3Request) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *SetDriveS3Request) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type SetDriveS3Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveS3Response) Reset() {
	*x = SetDriveS3Response{}
	mi := &file_proto_img_syncer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveS3Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveS3Response) ProtoMessage() {}

func (x *SetDriveS3Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveS3Response.ProtoReflect.Descriptor instead.
func (*SetDriveS3Response) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{24}
}

func (x *SetDriveS3Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetDriveS3Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListDriveS3BucketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveS3BucketsRequest) Reset() {
	*x = ListDriveS3BucketsRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveS3BucketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveS3BucketsRequest) ProtoMessage() {}

func (x *ListDriveS3BucketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveS3BucketsRequest.ProtoReflect.Descriptor instead.
func (*ListDriveS3BucketsRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{25}
}

type ListDriveS3BucketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Buckets       []string               `protobuf:"bytes,3,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriveS3BucketsResponse) Reset() {
	*x = ListDriveS3BucketsResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriveS3BucketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriveS3BucketsResponse) ProtoMessage() {}

func (x *ListDriveS3BucketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriveS3BucketsResponse.ProtoReflect.Descriptor instead.
func (*ListDriveS3BucketsResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{26}
}

func (x *ListDriveS3BucketsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListDriveS3BucketsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListDriveS3BucketsResponse) GetBuckets() []string {
	if x != nil {
		return x.Buckets
	}
	return nil
}

type MoveToTrashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToTrashRequest) Reset() {
	*x = MoveToTrashRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToTrashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToTrashRequest) ProtoMessage() {}

func (x *MoveToTrashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToTrashRequest.ProtoReflect.Descriptor instead.
func (*MoveToTrashRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{27}
}

func (x *MoveToTrashRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type MoveToTrashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToTrashResponse) Reset() {
	*x = MoveToTrashResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToTrashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToTrashResponse) ProtoMessage() {}

func (x *MoveToTrashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToTrashResponse.ProtoReflect.Descriptor instead.
func (*MoveToTrashResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{28}
}

func (x *MoveToTrashResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MoveToTrashResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TrashItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalPath  string                 `protobuf:"bytes,1,opt,name=originalPath,proto3" json:"originalPath,omitempty"`
	TrashPath     string                 `protobuf:"bytes,2,opt,name=trashPath,proto3" json:"trashPath,omitempty"`
	TrashedAt     int64                  `protobuf:"varint,3,opt,name=trashedAt,proto3" json:"trashedAt,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrashItem) Reset() {
	*x = TrashItem{}
	mi := &file_proto_img_syncer_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrashItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrashItem) ProtoMessage() {}

func (x *TrashItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrashItem.ProtoReflect.Descriptor instead.
func (*TrashItem) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{29}
}

func (x *TrashItem) GetOriginalPath() string {
	if x != nil {
		return x.OriginalPath
	}
	return ""
}

func (x *TrashItem) GetTrashPath() string {
	if x != nil {
		return x.TrashPath
	}
	return ""
}

func (x *TrashItem) GetTrashedAt() int64 {
	if x != nil {
		return x.TrashedAt
	}
	return 0
}

func (x *TrashItem) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListTrashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	MaxReturn     int32                  `protobuf:"varint,2,opt,name=maxReturn,proto3" json:"maxReturn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrashRequest) Reset() {
	*x = ListTrashRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrashRequest) ProtoMessage() {}

func (x *ListTrashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrashRequest.ProtoReflect.Descriptor instead.
func (*ListTrashRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{30}
}

func (x *ListTrashRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTrashRequest) GetMaxReturn() int32 {
	if x != nil {
		return x.MaxReturn
	}
	return 0
}

type ListTrashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Items         []*TrashItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrashResponse) Reset() {
	*x = ListTrashResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrashResponse) ProtoMessage() {}

func (x *ListTrashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrashResponse.ProtoReflect.Descriptor instead.
func (*ListTrashResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{31}
}

func (x *ListTrashResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListTrashResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListTrashResponse) GetItems() []*TrashItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RestoreFromTrashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrashPaths    []string               `protobuf:"bytes,1,rep,name=trashPaths,proto3" json:"trashPaths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFromTrashRequest) Reset() {
	*x = RestoreFromTrashRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromTrashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromTrashRequest) ProtoMessage() {}

func (x *RestoreFromTrashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFromTrashRequest.ProtoReflect.Descriptor instead.
func (*RestoreFromTrashRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{32}
}

func (x *RestoreFromTrashRequest) GetTrashPaths() []string {
	if x != nil {
		return x.TrashPaths
	}
	return nil
}

type RestoreFromTrashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFromTrashResponse) Reset() {
	*x = RestoreFromTrashResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromTrashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromTrashResponse) ProtoMessage() {}

func (x *RestoreFromTrashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFromTrashResponse.ProtoReflect.Descriptor instead.
func (*RestoreFromTrashResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{33}
}

func (x *RestoreFromTrashResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreFromTrashResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EmptyTrashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyTrashRequest) Reset() {
	*x = EmptyTrashRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyTrashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyTrashRequest) ProtoMessage() {}

func (x *EmptyTrashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyTrashRequest.ProtoReflect.Descriptor instead.
func (*EmptyTrashRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{34}
}

type EmptyTrashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyTrashResponse) Reset() {
	*x = EmptyTrashResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyTrashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyTrashResponse) ProtoMessage() {}

func (x *EmptyTrashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyTrashResponse.ProtoReflect.Descriptor instead.
func (*EmptyTrashResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{35}
}

func (x *EmptyTrashResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmptyTrashResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MoveToLockedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToLockedRequest) Reset() {
	*x = MoveToLockedRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToLockedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToLockedRequest) ProtoMessage() {}

func (x *MoveToLockedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToLockedRequest.ProtoReflect.Descriptor instead.
func (*MoveToLockedRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{36}
}

func (x *MoveToLockedRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type MoveToLockedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToLockedResponse) Reset() {
	*x = MoveToLockedResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToLockedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToLockedResponse) ProtoMessage() {}

func (x *MoveToLockedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToLockedResponse.ProtoReflect.Descriptor instead.
func (*MoveToLockedResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{37}
}

func (x *MoveToLockedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MoveToLockedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RestoreFromLockedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockedPaths   []string               `protobuf:"bytes,1,rep,name=lockedPaths,proto3" json:"lockedPaths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFromLockedRequest) Reset() {
	*x = RestoreFromLockedRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromLockedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromLockedRequest) ProtoMessage() {}

func (x *RestoreFromLockedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFromLockedRequest.ProtoReflect.Descriptor instead.
func (*RestoreFromLockedRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{38}
}

func (x *RestoreFromLockedRequest) GetLockedPaths() []string {
	if x != nil {
		return x.LockedPaths
	}
	return nil
}

type RestoreFromLockedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFromLockedResponse) Reset() {
	*x = RestoreFromLockedResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromLockedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromLockedResponse) ProtoMessage() {}

func (x *RestoreFromLockedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFromLockedResponse.ProtoReflect.Descriptor instead.
func (*RestoreFromLockedResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{39}
}

func (x *RestoreFromLockedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreFromLockedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListLockedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	MaxReturn     int32                  `protobuf:"varint,2,opt,name=maxReturn,proto3" json:"maxReturn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLockedRequest) Reset() {
	*x = ListLockedRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLockedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLockedRequest) ProtoMessage() {}

func (x *ListLockedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLockedRequest.ProtoReflect.Descriptor instead.
func (*ListLockedRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{40}
}

func (x *ListLockedRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListLockedRequest) GetMaxReturn() int32 {
	if x != nil {
		return x.MaxReturn
	}
	return 0
}

type ListLockedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Items         []*TrashItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLockedResponse) Reset() {
	*x = ListLockedResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLockedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLockedResponse) ProtoMessage() {}

func (x *ListLockedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLockedResponse.ProtoReflect.Descriptor instead.
func (*ListLockedResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{41}
}

func (x *ListLockedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListLockedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListLockedResponse) GetItems() []*TrashItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RebuildIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildIndexRequest) Reset() {
	*x = RebuildIndexRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildIndexRequest) ProtoMessage() {}

func (x *RebuildIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildIndexRequest.ProtoReflect.Descriptor instead.
func (*RebuildIndexRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{42}
}

type RebuildIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TotalFound    int32                  `protobuf:"varint,3,opt,name=totalFound,proto3" json:"totalFound,omitempty"`
	IsFinished    bool                   `protobuf:"varint,4,opt,name=isFinished,proto3" json:"isFinished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildIndexResponse) Reset() {
	*x = RebuildIndexResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildIndexResponse) ProtoMessage() {}

func (x *RebuildIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildIndexResponse.ProtoReflect.Descriptor instead.
func (*RebuildIndexResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{43}
}

func (x *RebuildIndexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RebuildIndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RebuildIndexResponse) GetTotalFound() int32 {
	if x != nil {
		return x.TotalFound
	}
	return 0
}

func (x *RebuildIndexResponse) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

type GetIndexStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexStatsRequest) Reset() {
	*x = GetIndexStatsRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexStatsRequest) ProtoMessage() {}

func (x *GetIndexStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexStatsRequest.ProtoReflect.Descriptor instead.
func (*GetIndexStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{44}
}

type GetIndexStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message            string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TotalPhotos        int64                  `protobuf:"varint,3,opt,name=totalPhotos,proto3" json:"totalPhotos,omitempty"`
	CacheSizeBytes     int64                  `protobuf:"varint,4,opt,name=cacheSizeBytes,proto3" json:"cacheSizeBytes,omitempty"`
	LastIndexTimestamp int64                  `protobuf:"varint,5,opt,name=lastIndexTimestamp,proto3" json:"lastIndexTimestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetIndexStatsResponse) Reset() {
	*x = GetIndexStatsResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexStatsResponse) ProtoMessage() {}

func (x *GetIndexStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexStatsResponse.ProtoReflect.Descriptor instead.
func (*GetIndexStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{45}
}

func (x *GetIndexStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetIndexStatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetIndexStatsResponse) GetTotalPhotos() int64 {
	if x != nil {
		return x.TotalPhotos
	}
	return 0
}

func (x *GetIndexStatsResponse) GetCacheSizeBytes() int64 {
	if x != nil {
		return x.CacheSizeBytes
	}
	return 0
}

func (x *GetIndexStatsResponse) GetLastIndexTimestamp() int64 {
	if x != nil {
		return x.LastIndexTimestamp
	}
	return 0
}

type ClearThumbnailCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearThumbnailCacheRequest) Reset() {
	*x = ClearThumbnailCacheRequest{}
	mi := &file_proto_img_syncer_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearThumbnailCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearThumbnailCacheRequest) ProtoMessage() {}

func (x *ClearThumbnailCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearThumbnailCacheRequest.ProtoReflect.Descriptor instead.
func (*ClearThumbnailCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{46}
}

type ClearThumbnailCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FreedBytes    int64                  `protobuf:"varint,3,opt,name=freedBytes,proto3" json:"freedBytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearThumbnailCacheResponse) Reset() {
	*x = ClearThumbnailCacheResponse{}
	mi := &file_proto_img_syncer_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearThumbnailCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearThumbnailCacheResponse) ProtoMessage() {}

func (x *ClearThumbnailCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_img_syncer_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearThumbnailCacheResponse.ProtoReflect.Descriptor instead.
func (*ClearThumbnailCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_img_syncer_proto_rawDescGZIP(), []int{47}
}

func (x *ClearThumbnailCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearThumbnailCacheResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClearThumbnailCacheResponse) GetFreedBytes() int64 {
	if x != nil {
		return x.FreedBytes
	}
	return 0
}

var File_proto_img_syncer_proto protoreflect.FileDescriptor

const file_proto_img_syncer_proto_rawDesc = "" +
	"\n" +
	"\x16proto/img_syncer.proto\x12\n" +
	"img_syncer\"]\n" +
	"\x11ListByDateRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1c\n" +
	"\tmaxReturn\x18\x03 \x01(\x05R\tmaxReturn\"^\n" +
	"\x12ListByDateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05paths\x18\x03 \x03(\tR\x05paths\"%\n" +
	"\rDeleteRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\x1cFilterNotUploadedRequestInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"|\n" +
	"\x18FilterNotUploadedRequest\x12@\n" +
	"\x06photos\x18\x01 \x03(\v2(.img_syncer.FilterNotUploadedRequestInfoR\x06photos\x12\x1e\n" +
	"\n" +
	"isFinished\x18\x02 \x01(\bR\n" +
	"isFinished\"\x95\x01\n" +
	"\x19FilterNotUploadedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\rnotUploaedIDs\x18\x03 \x03(\tR\rnotUploaedIDs\x12\x1e\n" +
	"\n" +
	"isFinished\x18\x04 \x01(\bR\n" +
	"isFinished\"\x8a\x01\n" +
	"\x12SetDriveSMBRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05share\x18\x04 \x01(\tR\x05share\x12\x12\n" +
	"\x04root\x18\x05 \x01(\tR\x04root\"I\n" +
	"\x13SetDriveSMBResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1b\n" +
	"\x19ListDriveSMBSharesRequest\"h\n" +
	"\x1aListDriveSMBSharesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06shares\x18\x03 \x03(\tR\x06shares\"@\n" +
	"\x16ListDriveSMBDirRequest\x12\x14\n" +
	"\x05share\x18\x01 \x01(\tR\x05share\x12\x10\n" +
	"\x03dir\x18\x02 \x01(\tR\x03dir\"a\n" +
	"\x17ListDriveSMBDirResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04dirs\x18\x03 \x03(\tR\x04dirs\"C\n" +
	"\x17SetDriveSMBShareRequest\x12\x14\n" +
	"\x05share\x18\x01 \x01(\tR\x05share\x12\x12\n" +
	"\x04root\x18\x02 \x01(\tR\x04root\"N\n" +
	"\x18SetDriveSMBShareResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"w\n" +
	"\x15SetDriveWebdavRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04root\x18\x04 \x01(\tR\x04root\"L\n" +
	"\x16SetDriveWebdavResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x19ListDriveWebdavDirRequest\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\"d\n" +
	"\x1aListDriveWebdavDirResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04dirs\x18\x03 \x03(\tR\x04dirs\"<\n" +
	"\x12SetDriveNFSRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04root\x18\x02 \x01(\tR\x04root\"I\n" +
	"\x13SetDriveNFSResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\x16ListDriveNFSDirRequest\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\"a\n" +
	"\x17ListDriveNFSDirResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04dirs\x18\x03 \x03(\tR\x04dirs\"\xbf\x01\n" +
	"\x11SetDriveS3Request\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12 \n" +
	"\vaccessKeyId\x18\x03 \x01(\tR\vaccessKeyId\x12(\n" +
	"\x0fsecretAccessKey\x18\x04 \x01(\tR\x0fsecretAccessKey\x12\x16\n" +
	"\x06bucket\x18\x05 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04root\x18\x06 \x01(\tR\x04root\"H\n" +
	"\x12SetDriveS3Response\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1b\n" +
	"\x19ListDriveS3BucketsRequest\"j\n" +
	"\x1aListDriveS3BucketsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\abuckets\x18\x03 \x03(\tR\abuckets\"*\n" +
	"\x12MoveToTrashRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"I\n" +
	"\x13MoveToTrashResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x7f\n" +
	"\tTrashItem\x12\"\n" +
	"\foriginalPath\x18\x01 \x01(\tR\foriginalPath\x12\x1c\n" +
	"\ttrashPath\x18\x02 \x01(\tR\ttrashPath\x12\x1c\n" +
	"\ttrashedAt\x18\x03 \x01(\x03R\ttrashedAt\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"H\n" +
	"\x10ListTrashRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x1c\n" +
	"\tmaxReturn\x18\x02 \x01(\x05R\tmaxReturn\"t\n" +
	"\x11ListTrashResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x05items\x18\x03 \x03(\v2\x15.img_syncer.TrashItemR\x05items\"9\n" +
	"\x17RestoreFromTrashRequest\x12\x1e\n" +
	"\n" +
	"trashPaths\x18\x01 \x03(\tR\n" +
	"trashPaths\"N\n" +
	"\x18RestoreFromTrashResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11EmptyTrashRequest\"H\n" +
	"\x12EmptyTrashResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\x13MoveToLockedRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"J\n" +
	"\x14MoveToLockedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"<\n" +
	"\x18RestoreFromLockedRequest\x12 \n" +
	"\vlockedPaths\x18\x01 \x03(\tR\vlockedPaths\"O\n" +
	"\x19RestoreFromLockedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x11ListLockedRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x1c\n" +
	"\tmaxReturn\x18\x02 \x01(\x05R\tmaxReturn\"u\n" +
	"\x12ListLockedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x05items\x18\x03 \x03(\v2\x15.img_syncer.TrashItemR\x05items\"\x15\n" +
	"\x13RebuildIndexRequest\"\x8a\x01\n" +
	"\x14RebuildIndexResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"totalFound\x18\x03 \x01(\x05R\n" +
	"totalFound\x12\x1e\n" +
	"\n" +
	"isFinished\x18\x04 \x01(\bR\n" +
	"isFinished\"\x16\n" +
	"\x14GetIndexStatsRequest\"\xc5\x01\n" +
	"\x15GetIndexStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\vtotalPhotos\x18\x03 \x01(\x03R\vtotalPhotos\x12&\n" +
	"\x0ecacheSizeBytes\x18\x04 \x01(\x03R\x0ecacheSizeBytes\x12.\n" +
	"\x12lastIndexTimestamp\x18\x05 \x01(\x03R\x12lastIndexTimestamp\"\x1c\n" +
	"\x1aClearThumbnailCacheRequest\"q\n" +
	"\x1bClearThumbnailCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"freedBytes\x18\x03 \x01(\x03R\n" +
	"freedBytes2\x94\x10\n" +
	"\tImgSyncer\x12M\n" +
	"\n" +
	"ListByDate\x12\x1d.img_syncer.ListByDateRequest\x1a\x1e.img_syncer.ListByDateResponse\"\x00\x12A\n" +
	"\x06Delete\x12\x19.img_syncer.DeleteRequest\x1a\x1a.img_syncer.DeleteResponse\"\x00\x12f\n" +
	"\x11FilterNotUploaded\x12$.img_syncer.FilterNotUploadedRequest\x1a%.img_syncer.FilterNotUploadedResponse\"\x00(\x010\x01\x12P\n" +
	"\vSetDriveSMB\x12\x1e.img_syncer.SetDriveSMBRequest\x1a\x1f.img_syncer.SetDriveSMBResponse\"\x00\x12e\n" +
	"\x12ListDriveSMBShares\x12%.img_syncer.ListDriveSMBSharesRequest\x1a&.img_syncer.ListDriveSMBSharesResponse\"\x00\x12\\\n" +
	"\x0fListDriveSMBDir\x12\".img_syncer.ListDriveSMBDirRequest\x1a#.img_syncer.ListDriveSMBDirResponse\"\x00\x12_\n" +
	"\x10SetDriveSMBShare\x12#.img_syncer.SetDriveSMBShareRequest\x1a$.img_syncer.SetDriveSMBShareResponse\"\x00\x12Y\n" +
	"\x0eSetDriveWebdav\x12!.img_syncer.SetDriveWebdavRequest\x1a\".img_syncer.SetDriveWebdavResponse\"\x00\x12e\n" +
	"\x12ListDriveWebdavDir\x12%.img_syncer.ListDriveWebdavDirRequest\x1a&.img_syncer.ListDriveWebdavDirResponse\"\x00\x12P\n" +
	"\vSetDriveNFS\x12\x1e.img_syncer.SetDriveNFSRequest\x1a\x1f.img_syncer.SetDriveNFSResponse\"\x00\x12\\\n" +
	"\x0fListDriveNFSDir\x12\".img_syncer.ListDriveNFSDirRequest\x1a#.img_syncer.ListDriveNFSDirResponse\"\x00\x12M\n" +
	"\n" +
	"SetDriveS3\x12\x1d.img_syncer.SetDriveS3Request\x1a\x1e.img_syncer.SetDriveS3Response\"\x00\x12e\n" +
	"\x12ListDriveS3Buckets\x12%.img_syncer.ListDriveS3BucketsRequest\x1a&.img_syncer.ListDriveS3BucketsResponse\"\x00\x12P\n" +
	"\vMoveToTrash\x12\x1e.img_syncer.MoveToTrashRequest\x1a\x1f.img_syncer.MoveToTrashResponse\"\x00\x12J\n" +
	"\tListTrash\x12\x1c.img_syncer.ListTrashRequest\x1a\x1d.img_syncer.ListTrashResponse\"\x00\x12_\n" +
	"\x10RestoreFromTrash\x12#.img_syncer.RestoreFromTrashRequest\x1a$.img_syncer.RestoreFromTrashResponse\"\x00\x12M\n" +
	"\n" +
	"EmptyTrash\x12\x1d.img_syncer.EmptyTrashRequest\x1a\x1e.img_syncer.EmptyTrashResponse\"\x00\x12S\n" +
	"\fMoveToLocked\x12\x1f.img_syncer.MoveToLockedRequest\x1a .img_syncer.MoveToLockedResponse\"\x00\x12M\n" +
	"\n" +
	"ListLocked\x12\x1d.img_syncer.ListLockedRequest\x1a\x1e.img_syncer.ListLockedResponse\"\x00\x12b\n" +
	"\x11RestoreFromLocked\x12$.img_syncer.RestoreFromLockedRequest\x1a%.img_syncer.RestoreFromLockedResponse\"\x00\x12U\n" +
	"\fRebuildIndex\x12\x1f.img_syncer.RebuildIndexRequest\x1a .img_syncer.RebuildIndexResponse\"\x000\x01\x12V\n" +
	"\rGetIndexStats\x12 .img_syncer.GetIndexStatsRequest\x1a!.img_syncer.GetIndexStatsResponse\"\x00\x12h\n" +
	"\x13ClearThumbnailCache\x12&.img_syncer.ClearThumbnailCacheRequest\x1a'.img_syncer.ClearThumbnailCacheResponse\"\x00B$Z\"github.com/fregie/img_syncer/protob\x06proto3"

var (
	file_proto_img_syncer_proto_rawDescOnce sync.Once
	file_proto_img_syncer_proto_rawDescData []byte
)

func file_proto_img_syncer_proto_rawDescGZIP() []byte {
	file_proto_img_syncer_proto_rawDescOnce.Do(func() {
		file_proto_img_syncer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_img_syncer_proto_rawDesc), len(file_proto_img_syncer_proto_rawDesc)))
	})
	return file_proto_img_syncer_proto_rawDescData
}

var file_proto_img_syncer_proto_msgTypes = make([]protoimpl.MessageInfo, 48)
var file_proto_img_syncer_proto_goTypes = []any{
	(*ListByDateRequest)(nil),            // 0: img_syncer.ListByDateRequest
	(*ListByDateResponse)(nil),           // 1: img_syncer.ListByDateResponse
	(*DeleteRequest)(nil),                // 2: img_syncer.DeleteRequest
	(*DeleteResponse)(nil),               // 3: img_syncer.DeleteResponse
	(*FilterNotUploadedRequestInfo)(nil), // 4: img_syncer.FilterNotUploadedRequestInfo
	(*FilterNotUploadedRequest)(nil),     // 5: img_syncer.FilterNotUploadedRequest
	(*FilterNotUploadedResponse)(nil),    // 6: img_syncer.FilterNotUploadedResponse
	(*SetDriveSMBRequest)(nil),           // 7: img_syncer.SetDriveSMBRequest
	(*SetDriveSMBResponse)(nil),          // 8: img_syncer.SetDriveSMBResponse
	(*ListDriveSMBSharesRequest)(nil),    // 9: img_syncer.ListDriveSMBSharesRequest
	(*ListDriveSMBSharesResponse)(nil),   // 10: img_syncer.ListDriveSMBSharesResponse
	(*ListDriveSMBDirRequest)(nil),       // 11: img_syncer.ListDriveSMBDirRequest
	(*ListDriveSMBDirResponse)(nil),      // 12: img_syncer.ListDriveSMBDirResponse
	(*SetDriveSMBShareRequest)(nil),      // 13: img_syncer.SetDriveSMBShareRequest
	(*SetDriveSMBShareResponse)(nil),     // 14: img_syncer.SetDriveSMBShareResponse
	(*SetDriveWebdavRequest)(nil),        // 15: img_syncer.SetDriveWebdavRequest
	(*SetDriveWebdavResponse)(nil),       // 16: img_syncer.SetDriveWebdavResponse
	(*ListDriveWebdavDirRequest)(nil),    // 17: img_syncer.ListDriveWebdavDirRequest
	(*ListDriveWebdavDirResponse)(nil),   // 18: img_syncer.ListDriveWebdavDirResponse
	(*SetDriveNFSRequest)(nil),           // 19: img_syncer.SetDriveNFSRequest
	(*SetDriveNFSResponse)(nil),          // 20: img_syncer.SetDriveNFSResponse
	(*ListDriveNFSDirRequest)(nil),       // 21: img_syncer.ListDriveNFSDirRequest
	(*ListDriveNFSDirResponse)(nil),      // 22: img_syncer.ListDriveNFSDirResponse
	(*SetDriveS3Request)(nil),            // 23: img_syncer.SetDriveS3Request
	(*SetDriveS3Response)(nil),           // 24: img_syncer.SetDriveS3Response
	(*ListDriveS3BucketsRequest)(nil),    // 25: img_syncer.ListDriveS3BucketsRequest
	(*ListDriveS3BucketsResponse)(nil),   // 26: img_syncer.ListDriveS3BucketsResponse
	(*MoveToTrashRequest)(nil),           // 27: img_syncer.MoveToTrashRequest
	(*MoveToTrashResponse)(nil),          // 28: img_syncer.MoveToTrashResponse
	(*TrashItem)(nil),                    // 29: img_syncer.TrashItem
	(*ListTrashRequest)(nil),             // 30: img_syncer.ListTrashRequest
	(*ListTrashResponse)(nil),            // 31: img_syncer.ListTrashResponse
	(*RestoreFromTrashRequest)(nil),      // 32: img_syncer.RestoreFromTrashRequest
	(*RestoreFromTrashResponse)(nil),     // 33: img_syncer.RestoreFromTrashResponse
	(*EmptyTrashRequest)(nil),            // 34: img_syncer.EmptyTrashRequest
	(*EmptyTrashResponse)(nil),           // 35: img_syncer.EmptyTrashResponse
	(*MoveToLockedRequest)(nil),          // 36: img_syncer.MoveToLockedRequest
	(*MoveToLockedResponse)(nil),         // 37: img_syncer.MoveToLockedResponse
	(*RestoreFromLockedRequest)(nil),     // 38: img_syncer.RestoreFromLockedRequest
	(*RestoreFromLockedResponse)(nil),    // 39: img_syncer.RestoreFromLockedResponse
	(*ListLockedRequest)(nil),            // 40: img_syncer.ListLockedRequest
	(*ListLockedResponse)(nil),           // 41: img_syncer.ListLockedResponse
	(*RebuildIndexRequest)(nil),          // 42: img_syncer.RebuildIndexRequest
	(*RebuildIndexResponse)(nil),         // 43: img_syncer.RebuildIndexResponse
	(*GetIndexStatsRequest)(nil),         // 44: img_syncer.GetIndexStatsRequest
	(*GetIndexStatsResponse)(nil),        // 45: img_syncer.GetIndexStatsResponse
	(*ClearThumbnailCacheRequest)(nil),   // 46: img_syncer.ClearThumbnailCacheRequest
	(*ClearThumbnailCacheResponse)(nil),  // 47: img_syncer.ClearThumbnailCacheResponse
}
var file_proto_img_syncer_proto_depIdxs = []int32{
	4,  // 0: img_syncer.FilterNotUploadedRequest.photos:type_name -> img_syncer.FilterNotUploadedRequestInfo
	29, // 1: img_syncer.ListTrashResponse.items:type_name -> img_syncer.TrashItem
	29, // 2: img_syncer.ListLockedResponse.items:type_name -> img_syncer.TrashItem
	0,  // 3: img_syncer.ImgSyncer.ListByDate:input_type -> img_syncer.ListByDateRequest
	2,  // 4: img_syncer.ImgSyncer.Delete:input_type -> img_syncer.DeleteRequest
	5,  // 5: img_syncer.ImgSyncer.FilterNotUploaded:input_type -> img_syncer.FilterNotUploadedRequest
	7,  // 6: img_syncer.ImgSyncer.SetDriveSMB:input_type -> img_syncer.SetDriveSMBRequest
	9,  // 7: img_syncer.ImgSyncer.ListDriveSMBShares:input_type -> img_syncer.ListDriveSMBSharesRequest
	11, // 8: img_syncer.ImgSyncer.ListDriveSMBDir:input_type -> img_syncer.ListDriveSMBDirRequest
	13, // 9: img_syncer.ImgSyncer.SetDriveSMBShare:input_type -> img_syncer.SetDriveSMBShareRequest
	15, // 10: img_syncer.ImgSyncer.SetDriveWebdav:input_type -> img_syncer.SetDriveWebdavRequest
	17, // 11: img_syncer.ImgSyncer.ListDriveWebdavDir:input_type -> img_syncer.ListDriveWebdavDirRequest
	19, // 12: img_syncer.ImgSyncer.SetDriveNFS:input_type -> img_syncer.SetDriveNFSRequest
	21, // 13: img_syncer.ImgSyncer.ListDriveNFSDir:input_type -> img_syncer.ListDriveNFSDirRequest
	23, // 14: img_syncer.ImgSyncer.SetDriveS3:input_type -> img_syncer.SetDriveS3Request
	25, // 15: img_syncer.ImgSyncer.ListDriveS3Buckets:input_type -> img_syncer.ListDriveS3BucketsRequest
	27, // 16: img_syncer.ImgSyncer.MoveToTrash:input_type -> img_syncer.MoveToTrashRequest
	30, // 17: img_syncer.ImgSyncer.ListTrash:input_type -> img_syncer.ListTrashRequest
	32, // 18: img_syncer.ImgSyncer.RestoreFromTrash:input_type -> img_syncer.RestoreFromTrashRequest
	34, // 19: img_syncer.ImgSyncer.EmptyTrash:input_type -> img_syncer.EmptyTrashRequest
	36, // 20: img_syncer.ImgSyncer.MoveToLocked:input_type -> img_syncer.MoveToLockedRequest
	40, // 21: img_syncer.ImgSyncer.ListLocked:input_type -> img_syncer.ListLockedRequest
	38, // 22: img_syncer.ImgSyncer.RestoreFromLocked:input_type -> img_syncer.RestoreFromLockedRequest
	42, // 23: img_syncer.ImgSyncer.RebuildIndex:input_type -> img_syncer.RebuildIndexRequest
	44, // 24: img_syncer.ImgSyncer.GetIndexStats:input_type -> img_syncer.GetIndexStatsRequest
	46, // 25: img_syncer.ImgSyncer.ClearThumbnailCache:input_type -> img_syncer.ClearThumbnailCacheRequest
	1,  // 26: img_syncer.ImgSyncer.ListByDate:output_type -> img_syncer.ListByDateResponse
	3,  // 27: img_syncer.ImgSyncer.Delete:output_type -> img_syncer.DeleteResponse
	6,  // 28: img_syncer.ImgSyncer.FilterNotUploaded:output_type -> img_syncer.FilterNotUploadedResponse
	8,  // 29: img_syncer.ImgSyncer.SetDriveSMB:output_type -> img_syncer.SetDriveSMBResponse
	10, // 30: img_syncer.ImgSyncer.ListDriveSMBShares:output_type -> img_syncer.ListDriveSMBSharesResponse
	12, // 31: img_syncer.ImgSyncer.ListDriveSMBDir:output_type -> img_syncer.ListDriveSMBDirResponse
	14, // 32: img_syncer.ImgSyncer.SetDriveSMBShare:output_type -> img_syncer.SetDriveSMBShareResponse
	16, // 33: img_syncer.ImgSyncer.SetDriveWebdav:output_type -> img_syncer.SetDriveWebdavResponse
	18, // 34: img_syncer.ImgSyncer.ListDriveWebdavDir:output_type -> img_syncer.ListDriveWebdavDirResponse
	20, // 35: img_syncer.ImgSyncer.SetDriveNFS:output_type -> img_syncer.SetDriveNFSResponse
	22, // 36: img_syncer.ImgSyncer.ListDriveNFSDir:output_type -> img_syncer.ListDriveNFSDirResponse
	24, // 37: img_syncer.ImgSyncer.SetDriveS3:output_type -> img_syncer.SetDriveS3Response
	26, // 38: img_syncer.ImgSyncer.ListDriveS3Buckets:output_type -> img_syncer.ListDriveS3BucketsResponse
	28, // 39: img_syncer.ImgSyncer.MoveToTrash:output_type -> img_syncer.MoveToTrashResponse
	31, // 40: img_syncer.ImgSyncer.ListTrash:output_type -> img_syncer.ListTrashResponse
	33, // 41: img_syncer.ImgSyncer.RestoreFromTrash:output_type -> img_syncer.RestoreFromTrashResponse
	35, // 42: img_syncer.ImgSyncer.EmptyTrash:output_type -> img_syncer.EmptyTrashResponse
	37, // 43: img_syncer.ImgSyncer.MoveToLocked:output_type -> img_syncer.MoveToLockedResponse
	41, // 44: img_syncer.ImgSyncer.ListLocked:output_type -> img_syncer.ListLockedResponse
	39, // 45: img_syncer.ImgSyncer.RestoreFromLocked:output_type -> img_syncer.RestoreFromLockedResponse
	43, // 46: img_syncer.ImgSyncer.RebuildIndex:output_type -> img_syncer.RebuildIndexResponse
	45, // 47: img_syncer.ImgSyncer.GetIndexStats:output_type -> img_syncer.GetIndexStatsResponse
	47, // 48: img_syncer.ImgSyncer.ClearThumbnailCache:output_type -> img_syncer.ClearThumbnailCacheResponse
	26, // [26:49] is the sub-list for method output_type
	3,  // [3:26] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_img_syncer_proto_init() }
func file_proto_img_syncer_proto_init() {
	if File_proto_img_syncer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_img_syncer_proto_rawDesc), len(file_proto_img_syncer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   48,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_img_syncer_proto_goTypes,
		DependencyIndexes: file_proto_img_syncer_proto_depIdxs,
		MessageInfos:      file_proto_img_syncer_proto_msgTypes,
	}.Build()
	File_proto_img_syncer_proto = out.File
	file_proto_img_syncer_proto_goTypes = nil
	file_proto_img_syncer_proto_depIdxs = nil
}
