// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proto/img_syncer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImgSyncer_ListByDate_FullMethodName             = "/img_syncer.ImgSyncer/ListByDate"
	ImgSyncer_Delete_FullMethodName                 = "/img_syncer.ImgSyncer/Delete"
	ImgSyncer_FilterNotUploaded_FullMethodName      = "/img_syncer.ImgSyncer/FilterNotUploaded"
	ImgSyncer_SetDriveSMB_FullMethodName            = "/img_syncer.ImgSyncer/SetDriveSMB"
	ImgSyncer_ListDriveSMBShares_FullMethodName     = "/img_syncer.ImgSyncer/ListDriveSMBShares"
	ImgSyncer_ListDriveSMBDir_FullMethodName        = "/img_syncer.ImgSyncer/ListDriveSMBDir"
	ImgSyncer_SetDriveSMBShare_FullMethodName       = "/img_syncer.ImgSyncer/SetDriveSMBShare"
	ImgSyncer_SetDriveWebdav_FullMethodName         = "/img_syncer.ImgSyncer/SetDriveWebdav"
	ImgSyncer_ListDriveWebdavDir_FullMethodName     = "/img_syncer.ImgSyncer/ListDriveWebdavDir"
	ImgSyncer_SetDriveNFS_FullMethodName            = "/img_syncer.ImgSyncer/SetDriveNFS"
	ImgSyncer_ListDriveNFSDir_FullMethodName        = "/img_syncer.ImgSyncer/ListDriveNFSDir"
	ImgSyncer_SetDriveBaiduNetDisk_FullMethodName   = "/img_syncer.ImgSyncer/SetDriveBaiduNetDisk"
	ImgSyncer_StartBaiduNetdiskLogin_FullMethodName = "/img_syncer.ImgSyncer/StartBaiduNetdiskLogin"
	ImgSyncer_MoveToTrash_FullMethodName            = "/img_syncer.ImgSyncer/MoveToTrash"
	ImgSyncer_ListTrash_FullMethodName              = "/img_syncer.ImgSyncer/ListTrash"
	ImgSyncer_RestoreFromTrash_FullMethodName       = "/img_syncer.ImgSyncer/RestoreFromTrash"
	ImgSyncer_EmptyTrash_FullMethodName             = "/img_syncer.ImgSyncer/EmptyTrash"
	ImgSyncer_RebuildIndex_FullMethodName           = "/img_syncer.ImgSyncer/RebuildIndex"
	ImgSyncer_GetIndexStats_FullMethodName          = "/img_syncer.ImgSyncer/GetIndexStats"
	ImgSyncer_ClearThumbnailCache_FullMethodName    = "/img_syncer.ImgSyncer/ClearThumbnailCache"
)

// ImgSyncerClient is the client API for ImgSyncer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImgSyncerClient interface {
	ListByDate(ctx context.Context, in *ListByDateRequest, opts ...grpc.CallOption) (*ListByDateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	FilterNotUploaded(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FilterNotUploadedRequest, FilterNotUploadedResponse], error)
	// SAMBA Drive
	SetDriveSMB(ctx context.Context, in *SetDriveSMBRequest, opts ...grpc.CallOption) (*SetDriveSMBResponse, error)
	ListDriveSMBShares(ctx context.Context, in *ListDriveSMBSharesRequest, opts ...grpc.CallOption) (*ListDriveSMBSharesResponse, error)
	ListDriveSMBDir(ctx context.Context, in *ListDriveSMBDirRequest, opts ...grpc.CallOption) (*ListDriveSMBDirResponse, error)
	SetDriveSMBShare(ctx context.Context, in *SetDriveSMBShareRequest, opts ...grpc.CallOption) (*SetDriveSMBShareResponse, error)
	// Webdav Drive
	SetDriveWebdav(ctx context.Context, in *SetDriveWebdavRequest, opts ...grpc.CallOption) (*SetDriveWebdavResponse, error)
	ListDriveWebdavDir(ctx context.Context, in *ListDriveWebdavDirRequest, opts ...grpc.CallOption) (*ListDriveWebdavDirResponse, error)
	// NFS Drive
	SetDriveNFS(ctx context.Context, in *SetDriveNFSRequest, opts ...grpc.CallOption) (*SetDriveNFSResponse, error)
	ListDriveNFSDir(ctx context.Context, in *ListDriveNFSDirRequest, opts ...grpc.CallOption) (*ListDriveNFSDirResponse, error)
	SetDriveBaiduNetDisk(ctx context.Context, in *SetDriveBaiduNetDiskRequest, opts ...grpc.CallOption) (*SetDriveBaiduNetDiskResponse, error)
	StartBaiduNetdiskLogin(ctx context.Context, in *StartBaiduNetdiskLoginRequest, opts ...grpc.CallOption) (*StartBaiduNetdiskLoginResponse, error)
	// Trash
	MoveToTrash(ctx context.Context, in *MoveToTrashRequest, opts ...grpc.CallOption) (*MoveToTrashResponse, error)
	ListTrash(ctx context.Context, in *ListTrashRequest, opts ...grpc.CallOption) (*ListTrashResponse, error)
	RestoreFromTrash(ctx context.Context, in *RestoreFromTrashRequest, opts ...grpc.CallOption) (*RestoreFromTrashResponse, error)
	EmptyTrash(ctx context.Context, in *EmptyTrashRequest, opts ...grpc.CallOption) (*EmptyTrashResponse, error)
	// Index management
	RebuildIndex(ctx context.Context, in *RebuildIndexRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RebuildIndexResponse], error)
	GetIndexStats(ctx context.Context, in *GetIndexStatsRequest, opts ...grpc.CallOption) (*GetIndexStatsResponse, error)
	ClearThumbnailCache(ctx context.Context, in *ClearThumbnailCacheRequest, opts ...grpc.CallOption) (*ClearThumbnailCacheResponse, error)
}

type imgSyncerClient struct {
	cc grpc.ClientConnInterface
}

func NewImgSyncerClient(cc grpc.ClientConnInterface) ImgSyncerClient {
	return &imgSyncerClient{cc}
}

func (c *imgSyncerClient) ListByDate(ctx context.Context, in *ListByDateRequest, opts ...grpc.CallOption) (*ListByDateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListByDateResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_ListByDate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) FilterNotUploaded(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FilterNotUploadedRequest, FilterNotUploadedResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ImgSyncer_ServiceDesc.Streams[0], ImgSyncer_FilterNotUploaded_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FilterNotUploadedRequest, FilterNotUploadedResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImgSyncer_FilterNotUploadedClient = grpc.BidiStreamingClient[FilterNotUploadedRequest, FilterNotUploadedResponse]

func (c *imgSyncerClient) SetDriveSMB(ctx context.Context, in *SetDriveSMBRequest, opts ...grpc.CallOption) (*SetDriveSMBResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDriveSMBResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_SetDriveSMB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) ListDriveSMBShares(ctx context.Context, in *ListDriveSMBSharesRequest, opts ...grpc.CallOption) (*ListDriveSMBSharesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDriveSMBSharesResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_ListDriveSMBShares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) ListDriveSMBDir(ctx context.Context, in *ListDriveSMBDirRequest, opts ...grpc.CallOption) (*ListDriveSMBDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDriveSMBDirResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_ListDriveSMBDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) SetDriveSMBShare(ctx context.Context, in *SetDriveSMBShareRequest, opts ...grpc.CallOption) (*SetDriveSMBShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDriveSMBShareResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_SetDriveSMBShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) SetDriveWebdav(ctx context.Context, in *SetDriveWebdavRequest, opts ...grpc.CallOption) (*SetDriveWebdavResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDriveWebdavResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_SetDriveWebdav_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) ListDriveWebdavDir(ctx context.Context, in *ListDriveWebdavDirRequest, opts ...grpc.CallOption) (*ListDriveWebdavDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDriveWebdavDirResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_ListDriveWebdavDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) SetDriveNFS(ctx context.Context, in *SetDriveNFSRequest, opts ...grpc.CallOption) (*SetDriveNFSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDriveNFSResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_SetDriveNFS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) ListDriveNFSDir(ctx context.Context, in *ListDriveNFSDirRequest, opts ...grpc.CallOption) (*ListDriveNFSDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDriveNFSDirResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_ListDriveNFSDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) SetDriveBaiduNetDisk(ctx context.Context, in *SetDriveBaiduNetDiskRequest, opts ...grpc.CallOption) (*SetDriveBaiduNetDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDriveBaiduNetDiskResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_SetDriveBaiduNetDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) StartBaiduNetdiskLogin(ctx context.Context, in *StartBaiduNetdiskLoginRequest, opts ...grpc.CallOption) (*StartBaiduNetdiskLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartBaiduNetdiskLoginResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_StartBaiduNetdiskLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) MoveToTrash(ctx context.Context, in *MoveToTrashRequest, opts ...grpc.CallOption) (*MoveToTrashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveToTrashResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_MoveToTrash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) ListTrash(ctx context.Context, in *ListTrashRequest, opts ...grpc.CallOption) (*ListTrashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrashResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_ListTrash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) RestoreFromTrash(ctx context.Context, in *RestoreFromTrashRequest, opts ...grpc.CallOption) (*RestoreFromTrashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreFromTrashResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_RestoreFromTrash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) EmptyTrash(ctx context.Context, in *EmptyTrashRequest, opts ...grpc.CallOption) (*EmptyTrashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyTrashResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_EmptyTrash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) RebuildIndex(ctx context.Context, in *RebuildIndexRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RebuildIndexResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ImgSyncer_ServiceDesc.Streams[1], ImgSyncer_RebuildIndex_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RebuildIndexRequest, RebuildIndexResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImgSyncer_RebuildIndexClient = grpc.ServerStreamingClient[RebuildIndexResponse]

func (c *imgSyncerClient) GetIndexStats(ctx context.Context, in *GetIndexStatsRequest, opts ...grpc.CallOption) (*GetIndexStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIndexStatsResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_GetIndexStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imgSyncerClient) ClearThumbnailCache(ctx context.Context, in *ClearThumbnailCacheRequest, opts ...grpc.CallOption) (*ClearThumbnailCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearThumbnailCacheResponse)
	err := c.cc.Invoke(ctx, ImgSyncer_ClearThumbnailCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImgSyncerServer is the server API for ImgSyncer service.
// All implementations must embed UnimplementedImgSyncerServer
// for forward compatibility.
type ImgSyncerServer interface {
	ListByDate(context.Context, *ListByDateRequest) (*ListByDateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	FilterNotUploaded(grpc.BidiStreamingServer[FilterNotUploadedRequest, FilterNotUploadedResponse]) error
	// SAMBA Drive
	SetDriveSMB(context.Context, *SetDriveSMBRequest) (*SetDriveSMBResponse, error)
	ListDriveSMBShares(context.Context, *ListDriveSMBSharesRequest) (*ListDriveSMBSharesResponse, error)
	ListDriveSMBDir(context.Context, *ListDriveSMBDirRequest) (*ListDriveSMBDirResponse, error)
	SetDriveSMBShare(context.Context, *SetDriveSMBShareRequest) (*SetDriveSMBShareResponse, error)
	// Webdav Drive
	SetDriveWebdav(context.Context, *SetDriveWebdavRequest) (*SetDriveWebdavResponse, error)
	ListDriveWebdavDir(context.Context, *ListDriveWebdavDirRequest) (*ListDriveWebdavDirResponse, error)
	// NFS Drive
	SetDriveNFS(context.Context, *SetDriveNFSRequest) (*SetDriveNFSResponse, error)
	ListDriveNFSDir(context.Context, *ListDriveNFSDirRequest) (*ListDriveNFSDirResponse, error)
	SetDriveBaiduNetDisk(context.Context, *SetDriveBaiduNetDiskRequest) (*SetDriveBaiduNetDiskResponse, error)
	StartBaiduNetdiskLogin(context.Context, *StartBaiduNetdiskLoginRequest) (*StartBaiduNetdiskLoginResponse, error)
	// Trash
	MoveToTrash(context.Context, *MoveToTrashRequest) (*MoveToTrashResponse, error)
	ListTrash(context.Context, *ListTrashRequest) (*ListTrashResponse, error)
	RestoreFromTrash(context.Context, *RestoreFromTrashRequest) (*RestoreFromTrashResponse, error)
	EmptyTrash(context.Context, *EmptyTrashRequest) (*EmptyTrashResponse, error)
	// Index management
	RebuildIndex(*RebuildIndexRequest, grpc.ServerStreamingServer[RebuildIndexResponse]) error
	GetIndexStats(context.Context, *GetIndexStatsRequest) (*GetIndexStatsResponse, error)
	ClearThumbnailCache(context.Context, *ClearThumbnailCacheRequest) (*ClearThumbnailCacheResponse, error)
	mustEmbedUnimplementedImgSyncerServer()
}

// UnimplementedImgSyncerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImgSyncerServer struct{}

func (UnimplementedImgSyncerServer) ListByDate(context.Context, *ListByDateRequest) (*ListByDateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListByDate not implemented")
}
func (UnimplementedImgSyncerServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedImgSyncerServer) FilterNotUploaded(grpc.BidiStreamingServer[FilterNotUploadedRequest, FilterNotUploadedResponse]) error {
	return status.Error(codes.Unimplemented, "method FilterNotUploaded not implemented")
}
func (UnimplementedImgSyncerServer) SetDriveSMB(context.Context, *SetDriveSMBRequest) (*SetDriveSMBResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDriveSMB not implemented")
}
func (UnimplementedImgSyncerServer) ListDriveSMBShares(context.Context, *ListDriveSMBSharesRequest) (*ListDriveSMBSharesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDriveSMBShares not implemented")
}
func (UnimplementedImgSyncerServer) ListDriveSMBDir(context.Context, *ListDriveSMBDirRequest) (*ListDriveSMBDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDriveSMBDir not implemented")
}
func (UnimplementedImgSyncerServer) SetDriveSMBShare(context.Context, *SetDriveSMBShareRequest) (*SetDriveSMBShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDriveSMBShare not implemented")
}
func (UnimplementedImgSyncerServer) SetDriveWebdav(context.Context, *SetDriveWebdavRequest) (*SetDriveWebdavResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDriveWebdav not implemented")
}
func (UnimplementedImgSyncerServer) ListDriveWebdavDir(context.Context, *ListDriveWebdavDirRequest) (*ListDriveWebdavDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDriveWebdavDir not implemented")
}
func (UnimplementedImgSyncerServer) SetDriveNFS(context.Context, *SetDriveNFSRequest) (*SetDriveNFSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDriveNFS not implemented")
}
func (UnimplementedImgSyncerServer) ListDriveNFSDir(context.Context, *ListDriveNFSDirRequest) (*ListDriveNFSDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDriveNFSDir not implemented")
}
func (UnimplementedImgSyncerServer) SetDriveBaiduNetDisk(context.Context, *SetDriveBaiduNetDiskRequest) (*SetDriveBaiduNetDiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDriveBaiduNetDisk not implemented")
}
func (UnimplementedImgSyncerServer) StartBaiduNetdiskLogin(context.Context, *StartBaiduNetdiskLoginRequest) (*StartBaiduNetdiskLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartBaiduNetdiskLogin not implemented")
}
func (UnimplementedImgSyncerServer) MoveToTrash(context.Context, *MoveToTrashRequest) (*MoveToTrashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveToTrash not implemented")
}
func (UnimplementedImgSyncerServer) ListTrash(context.Context, *ListTrashRequest) (*ListTrashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrash not implemented")
}
func (UnimplementedImgSyncerServer) RestoreFromTrash(context.Context, *RestoreFromTrashRequest) (*RestoreFromTrashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreFromTrash not implemented")
}
func (UnimplementedImgSyncerServer) EmptyTrash(context.Context, *EmptyTrashRequest) (*EmptyTrashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmptyTrash not implemented")
}
func (UnimplementedImgSyncerServer) RebuildIndex(*RebuildIndexRequest, grpc.ServerStreamingServer[RebuildIndexResponse]) error {
	return status.Error(codes.Unimplemented, "method RebuildIndex not implemented")
}
func (UnimplementedImgSyncerServer) GetIndexStats(context.Context, *GetIndexStatsRequest) (*GetIndexStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIndexStats not implemented")
}
func (UnimplementedImgSyncerServer) ClearThumbnailCache(context.Context, *ClearThumbnailCacheRequest) (*ClearThumbnailCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearThumbnailCache not implemented")
}
func (UnimplementedImgSyncerServer) mustEmbedUnimplementedImgSyncerServer() {}
func (UnimplementedImgSyncerServer) testEmbeddedByValue()                   {}

// UnsafeImgSyncerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImgSyncerServer will
// result in compilation errors.
type UnsafeImgSyncerServer interface {
	mustEmbedUnimplementedImgSyncerServer()
}

func RegisterImgSyncerServer(s grpc.ServiceRegistrar, srv ImgSyncerServer) {
	// If the following call panics, it indicates UnimplementedImgSyncerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImgSyncer_ServiceDesc, srv)
}

func _ImgSyncer_ListByDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListByDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).ListByDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_ListByDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).ListByDate(ctx, req.(*ListByDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_FilterNotUploaded_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImgSyncerServer).FilterNotUploaded(&grpc.GenericServerStream[FilterNotUploadedRequest, FilterNotUploadedResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImgSyncer_FilterNotUploadedServer = grpc.BidiStreamingServer[FilterNotUploadedRequest, FilterNotUploadedResponse]

func _ImgSyncer_SetDriveSMB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDriveSMBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).SetDriveSMB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_SetDriveSMB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).SetDriveSMB(ctx, req.(*SetDriveSMBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_ListDriveSMBShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDriveSMBSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).ListDriveSMBShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_ListDriveSMBShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).ListDriveSMBShares(ctx, req.(*ListDriveSMBSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_ListDriveSMBDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDriveSMBDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).ListDriveSMBDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_ListDriveSMBDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).ListDriveSMBDir(ctx, req.(*ListDriveSMBDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_SetDriveSMBShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDriveSMBShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).SetDriveSMBShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_SetDriveSMBShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).SetDriveSMBShare(ctx, req.(*SetDriveSMBShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_SetDriveWebdav_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDriveWebdavRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).SetDriveWebdav(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_SetDriveWebdav_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).SetDriveWebdav(ctx, req.(*SetDriveWebdavRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_ListDriveWebdavDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDriveWebdavDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).ListDriveWebdavDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_ListDriveWebdavDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).ListDriveWebdavDir(ctx, req.(*ListDriveWebdavDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_SetDriveNFS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDriveNFSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).SetDriveNFS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_SetDriveNFS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).SetDriveNFS(ctx, req.(*SetDriveNFSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_ListDriveNFSDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDriveNFSDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).ListDriveNFSDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_ListDriveNFSDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).ListDriveNFSDir(ctx, req.(*ListDriveNFSDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_SetDriveBaiduNetDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDriveBaiduNetDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).SetDriveBaiduNetDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_SetDriveBaiduNetDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).SetDriveBaiduNetDisk(ctx, req.(*SetDriveBaiduNetDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_StartBaiduNetdiskLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBaiduNetdiskLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).StartBaiduNetdiskLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_StartBaiduNetdiskLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).StartBaiduNetdiskLogin(ctx, req.(*StartBaiduNetdiskLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_MoveToTrash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveToTrashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).MoveToTrash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_MoveToTrash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).MoveToTrash(ctx, req.(*MoveToTrashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_ListTrash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).ListTrash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_ListTrash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).ListTrash(ctx, req.(*ListTrashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_RestoreFromTrash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreFromTrashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).RestoreFromTrash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_RestoreFromTrash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).RestoreFromTrash(ctx, req.(*RestoreFromTrashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_EmptyTrash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyTrashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).EmptyTrash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_EmptyTrash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).EmptyTrash(ctx, req.(*EmptyTrashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_RebuildIndex_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RebuildIndexRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImgSyncerServer).RebuildIndex(m, &grpc.GenericServerStream[RebuildIndexRequest, RebuildIndexResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImgSyncer_RebuildIndexServer = grpc.ServerStreamingServer[RebuildIndexResponse]

func _ImgSyncer_GetIndexStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).GetIndexStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_GetIndexStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).GetIndexStats(ctx, req.(*GetIndexStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImgSyncer_ClearThumbnailCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearThumbnailCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgSyncerServer).ClearThumbnailCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImgSyncer_ClearThumbnailCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgSyncerServer).ClearThumbnailCache(ctx, req.(*ClearThumbnailCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImgSyncer_ServiceDesc is the grpc.ServiceDesc for ImgSyncer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImgSyncer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "img_syncer.ImgSyncer",
	HandlerType: (*ImgSyncerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListByDate",
			Handler:    _ImgSyncer_ListByDate_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ImgSyncer_Delete_Handler,
		},
		{
			MethodName: "SetDriveSMB",
			Handler:    _ImgSyncer_SetDriveSMB_Handler,
		},
		{
			MethodName: "ListDriveSMBShares",
			Handler:    _ImgSyncer_ListDriveSMBShares_Handler,
		},
		{
			MethodName: "ListDriveSMBDir",
			Handler:    _ImgSyncer_ListDriveSMBDir_Handler,
		},
		{
			MethodName: "SetDriveSMBShare",
			Handler:    _ImgSyncer_SetDriveSMBShare_Handler,
		},
		{
			MethodName: "SetDriveWebdav",
			Handler:    _ImgSyncer_SetDriveWebdav_Handler,
		},
		{
			MethodName: "ListDriveWebdavDir",
			Handler:    _ImgSyncer_ListDriveWebdavDir_Handler,
		},
		{
			MethodName: "SetDriveNFS",
			Handler:    _ImgSyncer_SetDriveNFS_Handler,
		},
		{
			MethodName: "ListDriveNFSDir",
			Handler:    _ImgSyncer_ListDriveNFSDir_Handler,
		},
		{
			MethodName: "SetDriveBaiduNetDisk",
			Handler:    _ImgSyncer_SetDriveBaiduNetDisk_Handler,
		},
		{
			MethodName: "StartBaiduNetdiskLogin",
			Handler:    _ImgSyncer_StartBaiduNetdiskLogin_Handler,
		},
		{
			MethodName: "MoveToTrash",
			Handler:    _ImgSyncer_MoveToTrash_Handler,
		},
		{
			MethodName: "ListTrash",
			Handler:    _ImgSyncer_ListTrash_Handler,
		},
		{
			MethodName: "RestoreFromTrash",
			Handler:    _ImgSyncer_RestoreFromTrash_Handler,
		},
		{
			MethodName: "EmptyTrash",
			Handler:    _ImgSyncer_EmptyTrash_Handler,
		},
		{
			MethodName: "GetIndexStats",
			Handler:    _ImgSyncer_GetIndexStats_Handler,
		},
		{
			MethodName: "ClearThumbnailCache",
			Handler:    _ImgSyncer_ClearThumbnailCache_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FilterNotUploaded",
			Handler:       _ImgSyncer_FilterNotUploaded_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RebuildIndex",
			Handler:       _ImgSyncer_RebuildIndex_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/img_syncer.proto",
}
